<?php

declare(strict_types=1);

namespace Omp\Event;

// Code generated by tools/codegen. DO NOT EDIT.

final class Events
{
    /** Handler: function(int $actor, int $forPlayer); default result: true. */
    public const ACTOR_STREAM_IN = 'ActorStreamIn';
    /** Handler: function(int $actor, int $forPlayer); default result: true. */
    public const ACTOR_STREAM_OUT = 'ActorStreamOut';
    /** Handler: function(int $player, int $actionType, int $address, int $result); default result: true. */
    public const CLIENT_CHECK_RESPONSE = 'ClientCheckResponse';
    /** Handler: function(string $command, string $parameters); default result: true. */
    public const CONSOLE_TEXT = 'ConsoleText';
    /** Handler: function(int $player, int $dialogId, int $response, int $listItem, string $inputText); default result: true. */
    public const DIALOG_RESPONSE = 'DialogResponse';
    /** Handler: function(int $player, int $enterexit, int $interiorId); default result: true. */
    public const ENTER_EXIT_MOD_SHOP = 'EnterExitModShop';
    /** Handler: function(int $player, string $ipAddress, int $port); default result: true. */
    public const INCOMING_CONNECTION = 'IncomingConnection';
    /** Handler: function(int $npc, int $newNodeId, int $oldNodeId); default result: false. */
    public const NPC_CHANGE_NODE = 'NPCChangeNode';
    /** Handler: function(int $npc); default result: true. */
    public const NPC_CREATE = 'NPCCreate';
    /** Handler: function(int $npc, int $killer, int $reason); default result: true. */
    public const NPC_DEATH = 'NPCDeath';
    /** Handler: function(int $npc); default result: true. */
    public const NPC_DESTROY = 'NPCDestroy';
    /** Handler: function(int $npc); default result: true. */
    public const NPC_FINISH_MOVE = 'NPCFinishMove';
    /** Handler: function(int $npc, int $pathId); default result: true. */
    public const NPC_FINISH_MOVE_PATH = 'NPCFinishMovePath';
    /** Handler: function(int $npc, int $pathId, int $pointId); default result: true. */
    public const NPC_FINISH_MOVE_PATH_POINT = 'NPCFinishMovePathPoint';
    /** Handler: function(int $npc, int $nodeId); default result: true. */
    public const NPC_FINISH_NODE = 'NPCFinishNode';
    /** Handler: function(int $npc, int $nodeId, int $pointId); default result: true. */
    public const NPC_FINISH_NODE_POINT = 'NPCFinishNodePoint';
    /** Handler: function(int $npc, int $damaged, float $damage, int $weapon, int $bodyPart); default result: true. */
    public const NPC_GIVE_DAMAGE = 'NPCGiveDamage';
    /** Handler: function(int $npc, int $recordId); default result: true. */
    public const NPC_PLAYBACK_END = 'NPCPlaybackEnd';
    /** Handler: function(int $npc, int $recordId); default result: true. */
    public const NPC_PLAYBACK_START = 'NPCPlaybackStart';
    /** Handler: function(int $npc); default result: true. */
    public const NPC_RESPAWN = 'NPCRespawn';
    /** Handler: function(int $npc, int $weapon, float $offsetX, float $offsetY, float $offsetZ); default result: false. */
    public const NPC_SHOT_MISSED = 'NPCShotMissed';
    /** Handler: function(int $npc, int $npcTarget, int $weapon, float $offsetX, float $offsetY, float $offsetZ); default result: false. */
    public const NPC_SHOT_NPC = 'NPCShotNPC';
    /** Handler: function(int $npc, int $object, int $weapon, float $offsetX, float $offsetY, float $offsetZ); default result: false. */
    public const NPC_SHOT_OBJECT = 'NPCShotObject';
    /** Handler: function(int $npc, int $player, int $weapon, float $offsetX, float $offsetY, float $offsetZ); default result: false. */
    public const NPC_SHOT_PLAYER = 'NPCShotPlayer';
    /** Handler: function(int $npc, int $playerObject, int $weapon, float $offsetX, float $offsetY, float $offsetZ); default result: false. */
    public const NPC_SHOT_PLAYER_OBJECT = 'NPCShotPlayerObject';
    /** Handler: function(int $npc, int $vehicle, int $weapon, float $offsetX, float $offsetY, float $offsetZ); default result: false. */
    public const NPC_SHOT_VEHICLE = 'NPCShotVehicle';
    /** Handler: function(int $npc); default result: true. */
    public const NPC_SPAWN = 'NPCSpawn';
    /** Handler: function(int $npc, int $damager, float $damage, int $weapon, int $bodyPart); default result: false. */
    public const NPC_TAKE_DAMAGE = 'NPCTakeDamage';
    /** Handler: function(int $npc, int $newState, int $oldState); default result: true. */
    public const NPC_WEAPON_STATE_CHANGE = 'NPCWeaponStateChange';
    /** Handler: function(int $object); default result: true. */
    public const OBJECT_MOVE = 'ObjectMove';
    /** Handler: function(int $player); default result: true. */
    public const PLAYER_CANCEL_PLAYER_TEXT_DRAW_SELECTION = 'PlayerCancelPlayerTextDrawSelection';
    /** Handler: function(int $player); default result: true. */
    public const PLAYER_CANCEL_TEXT_DRAW_SELECTION = 'PlayerCancelTextDrawSelection';
    /** Handler: function(int $player, int $zone); default result: true. */
    public const PLAYER_CLICK_GANG_ZONE = 'PlayerClickGangZone';
    /** Handler: function(int $player, float $x, float $y, float $z); default result: true. */
    public const PLAYER_CLICK_MAP = 'PlayerClickMap';
    /** Handler: function(int $player, int $clicked, int $source); default result: true. */
    public const PLAYER_CLICK_PLAYER = 'PlayerClickPlayer';
    /** Handler: function(int $player, int $textdraw); default result: true. */
    public const PLAYER_CLICK_PLAYER_TEXT_DRAW = 'PlayerClickPlayerTextDraw';
    /** Handler: function(int $player, int $textdraw); default result: true. */
    public const PLAYER_CLICK_TEXT_DRAW = 'PlayerClickTextDraw';
    /** Handler: function(int $player, string $command); default result: true. */
    public const PLAYER_COMMAND_TEXT = 'PlayerCommandText';
    /** Handler: function(int $player); default result: true. */
    public const PLAYER_CONNECT = 'PlayerConnect';
    /** Handler: function(int $player, int $killer, int $reason); default result: true. */
    public const PLAYER_DEATH = 'PlayerDeath';
    /** Handler: function(int $player, int $reason); default result: true. */
    public const PLAYER_DISCONNECT = 'PlayerDisconnect';
    /** Handler: function(int $player, bool $saved, int $index, int $model, int $bone, float $offsetX, float $offsetY, float $offsetZ, float $rotationX, float $rotationY, float $rotationZ, float $scaleX, float $scaleY, float $scaleZ); default result: true. */
    public const PLAYER_EDIT_ATTACHED_OBJECT = 'PlayerEditAttachedObject';
    /** Handler: function(int $player, int $object, int $response, float $offsetX, float $offsetY, float $offsetZ, float $rotationX, float $rotationY, float $rotationZ); default result: true. */
    public const PLAYER_EDIT_OBJECT = 'PlayerEditObject';
    /** Handler: function(int $player, int $object, int $response, float $offsetX, float $offsetY, float $offsetZ, float $rotationX, float $rotationY, float $rotationZ); default result: true. */
    public const PLAYER_EDIT_PLAYER_OBJECT = 'PlayerEditPlayerObject';
    /** Handler: function(int $player); default result: true. */
    public const PLAYER_ENTER_CHECKPOINT = 'PlayerEnterCheckpoint';
    /** Handler: function(int $player, int $zone); default result: true. */
    public const PLAYER_ENTER_GANG_ZONE = 'PlayerEnterGangZone';
    /** Handler: function(int $player); default result: true. */
    public const PLAYER_ENTER_RACE_CHECKPOINT = 'PlayerEnterRaceCheckpoint';
    /** Handler: function(int $player, int $vehicle, bool $passenger); default result: true. */
    public const PLAYER_ENTER_VEHICLE = 'PlayerEnterVehicle';
    /** Handler: function(int $player, int $vehicle); default result: true. */
    public const PLAYER_EXIT_VEHICLE = 'PlayerExitVehicle';
    /** Handler: function(int $player); default result: true. */
    public const PLAYER_EXITED_MENU = 'PlayerExitedMenu';
    /** Handler: function(int $player, int $vw); default result: true. */
    public const PLAYER_FINISHED_DOWNLOADING = 'PlayerFinishedDownloading';
    /** Handler: function(int $player, int $to, float $amount, int $weapon, int $bodypart); default result: true. */
    public const PLAYER_GIVE_DAMAGE = 'PlayerGiveDamage';
    /** Handler: function(int $player, int $actor, float $amount, int $weapon, int $part); default result: true. */
    public const PLAYER_GIVE_DAMAGE_ACTOR = 'PlayerGiveDamageActor';
    /** Handler: function(int $player, int $newInterior, int $oldInterior); default result: true. */
    public const PLAYER_INTERIOR_CHANGE = 'PlayerInteriorChange';
    /** Handler: function(int $player, int $newKeys, int $oldKeys); default result: true. */
    public const PLAYER_KEY_STATE_CHANGE = 'PlayerKeyStateChange';
    /** Handler: function(int $player); default result: true. */
    public const PLAYER_LEAVE_CHECKPOINT = 'PlayerLeaveCheckpoint';
    /** Handler: function(int $player, int $zone); default result: true. */
    public const PLAYER_LEAVE_GANG_ZONE = 'PlayerLeaveGangZone';
    /** Handler: function(int $player); default result: true. */
    public const PLAYER_LEAVE_RACE_CHECKPOINT = 'PlayerLeaveRaceCheckpoint';
    /** Handler: function(int $player, int $object); default result: true. */
    public const PLAYER_OBJECT_MOVE = 'PlayerObjectMove';
    /** Handler: function(int $player, int $pickup); default result: true. */
    public const PLAYER_PICK_UP_PICKUP = 'PlayerPickUpPickup';
    /** Handler: function(int $player, int $classId); default result: false. */
    public const PLAYER_REQUEST_CLASS = 'PlayerRequestClass';
    /** Handler: function(int $player, int $type, int $checksum); default result: true. */
    public const PLAYER_REQUEST_DOWNLOAD = 'PlayerRequestDownload';
    /** Handler: function(int $player); default result: false. */
    public const PLAYER_REQUEST_SPAWN = 'PlayerRequestSpawn';
    /** Handler: function(int $player, int $object, int $model, float $x, float $y, float $z); default result: true. */
    public const PLAYER_SELECT_OBJECT = 'PlayerSelectObject';
    /** Handler: function(int $player, int $object, int $model, float $x, float $y, float $z); default result: true. */
    public const PLAYER_SELECT_PLAYER_OBJECT = 'PlayerSelectPlayerObject';
    /** Handler: function(int $player, int $row); default result: true. */
    public const PLAYER_SELECTED_MENU_ROW = 'PlayerSelectedMenuRow';
    /** Handler: function(int $player, int $weapon, float $x, float $y, float $z); default result: false. */
    public const PLAYER_SHOT_MISSED = 'PlayerShotMissed';
    /** Handler: function(int $player, int $target, int $weapon, float $x, float $y, float $z); default result: false. */
    public const PLAYER_SHOT_OBJECT = 'PlayerShotObject';
    /** Handler: function(int $player, int $target, int $weapon, float $x, float $y, float $z); default result: false. */
    public const PLAYER_SHOT_PLAYER = 'PlayerShotPlayer';
    /** Handler: function(int $player, int $target, int $weapon, float $x, float $y, float $z); default result: false. */
    public const PLAYER_SHOT_PLAYER_OBJECT = 'PlayerShotPlayerObject';
    /** Handler: function(int $player, int $target, int $weapon, float $x, float $y, float $z); default result: false. */
    public const PLAYER_SHOT_VEHICLE = 'PlayerShotVehicle';
    /** Handler: function(int $player); default result: true. */
    public const PLAYER_SPAWN = 'PlayerSpawn';
    /** Handler: function(int $player, int $newState, int $oldState); default result: true. */
    public const PLAYER_STATE_CHANGE = 'PlayerStateChange';
    /** Handler: function(int $player, int $forPlayer); default result: true. */
    public const PLAYER_STREAM_IN = 'PlayerStreamIn';
    /** Handler: function(int $player, int $forPlayer); default result: true. */
    public const PLAYER_STREAM_OUT = 'PlayerStreamOut';
    /** Handler: function(int $player, int $from, float $amount, int $weapon, int $bodypart); default result: true. */
    public const PLAYER_TAKE_DAMAGE = 'PlayerTakeDamage';
    /** Handler: function(int $player, string $text); default result: false. */
    public const PLAYER_TEXT = 'PlayerText';
    /** Handler: function(int $player); default result: false. */
    public const PLAYER_UPDATE = 'PlayerUpdate';
    /** Handler: function(string $address, string $password, bool $success); default result: true. */
    public const RCON_LOGIN_ATTEMPT = 'RconLoginAttempt';
    /** Handler: function(int $elapsed); default result: true. */
    public const TICK = 'Tick';
    /** Handler: function(int $player, int $trailer); default result: false. */
    public const TRAILER_UPDATE = 'TrailerUpdate';
    /** Handler: function(int $vehicle, int $player, int $seat, float $posX, float $posY, float $posZ, float $velocityX, float $velocityY, float $velocityZ); default result: false. */
    public const UNOCCUPIED_VEHICLE_UPDATE = 'UnoccupiedVehicleUpdate';
    /** Handler: function(int $vehicle, int $player); default result: true. */
    public const VEHICLE_DAMAGE_STATUS_UPDATE = 'VehicleDamageStatusUpdate';
    /** Handler: function(int $vehicle, int $player); default result: true. */
    public const VEHICLE_DEATH = 'VehicleDeath';
    /** Handler: function(int $player, int $vehicle, int $component); default result: false. */
    public const VEHICLE_MOD = 'VehicleMod';
    /** Handler: function(int $player, int $vehicle, int $paintJob); default result: false. */
    public const VEHICLE_PAINT_JOB = 'VehiclePaintJob';
    /** Handler: function(int $player, int $vehicle, int $color1, int $color2); default result: false. */
    public const VEHICLE_RESPRAY = 'VehicleRespray';
    /** Handler: function(int $player, int $vehicle, int $sirenState); default result: false. */
    public const VEHICLE_SIREN_STATE_CHANGE = 'VehicleSirenStateChange';
    /** Handler: function(int $vehicle); default result: true. */
    public const VEHICLE_SPAWN = 'VehicleSpawn';
    /** Handler: function(int $vehicle, int $player); default result: true. */
    public const VEHICLE_STREAM_IN = 'VehicleStreamIn';
    /** Handler: function(int $vehicle, int $player); default result: true. */
    public const VEHICLE_STREAM_OUT = 'VehicleStreamOut';
}
