<?php

declare(strict_types=1);

namespace Omp\Event;

// Code generated by tools/codegen. DO NOT EDIT.

final class Handlers
{
    /** @param callable(int, int): mixed $handler */
    public static function actorStreamIn(callable $handler): void
    {
        \Omp\Server::on(Events::ACTOR_STREAM_IN, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function actorStreamOut(callable $handler): void
    {
        \Omp\Server::on(Events::ACTOR_STREAM_OUT, $handler);
    }

    /** @param callable(int, int, int, int): mixed $handler */
    public static function clientCheckResponse(callable $handler): void
    {
        \Omp\Server::on(Events::CLIENT_CHECK_RESPONSE, $handler);
    }

    /** @param callable(string, string): mixed $handler */
    public static function consoleText(callable $handler): void
    {
        \Omp\Server::on(Events::CONSOLE_TEXT, $handler);
    }

    /** @param callable(int, int, int, int, string): mixed $handler */
    public static function dialogResponse(callable $handler): void
    {
        \Omp\Server::on(Events::DIALOG_RESPONSE, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function enterExitModShop(callable $handler): void
    {
        \Omp\Server::on(Events::ENTER_EXIT_MOD_SHOP, $handler);
    }

    /** @param callable(int, string, int): mixed $handler */
    public static function incomingConnection(callable $handler): void
    {
        \Omp\Server::on(Events::INCOMING_CONNECTION, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function npcChangeNode(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_CHANGE_NODE, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function npcCreate(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_CREATE, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function npcDeath(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_DEATH, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function npcDestroy(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_DESTROY, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function npcFinishMove(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_FINISH_MOVE, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function npcFinishMovePath(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_FINISH_MOVE_PATH, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function npcFinishMovePathPoint(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_FINISH_MOVE_PATH_POINT, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function npcFinishNode(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_FINISH_NODE, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function npcFinishNodePoint(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_FINISH_NODE_POINT, $handler);
    }

    /** @param callable(int, int, float, int, int): mixed $handler */
    public static function npcGiveDamage(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_GIVE_DAMAGE, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function npcPlaybackEnd(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_PLAYBACK_END, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function npcPlaybackStart(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_PLAYBACK_START, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function npcRespawn(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_RESPAWN, $handler);
    }

    /** @param callable(int, int, float, float, float): mixed $handler */
    public static function npcShotMissed(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_SHOT_MISSED, $handler);
    }

    /** @param callable(int, int, int, float, float, float): mixed $handler */
    public static function npcShotNpc(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_SHOT_NPC, $handler);
    }

    /** @param callable(int, int, int, float, float, float): mixed $handler */
    public static function npcShotObject(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_SHOT_OBJECT, $handler);
    }

    /** @param callable(int, int, int, float, float, float): mixed $handler */
    public static function npcShotPlayer(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_SHOT_PLAYER, $handler);
    }

    /** @param callable(int, int, int, float, float, float): mixed $handler */
    public static function npcShotPlayerObject(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_SHOT_PLAYER_OBJECT, $handler);
    }

    /** @param callable(int, int, int, float, float, float): mixed $handler */
    public static function npcShotVehicle(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_SHOT_VEHICLE, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function npcSpawn(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_SPAWN, $handler);
    }

    /** @param callable(int, int, float, int, int): mixed $handler */
    public static function npcTakeDamage(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_TAKE_DAMAGE, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function npcWeaponStateChange(callable $handler): void
    {
        \Omp\Server::on(Events::NPC_WEAPON_STATE_CHANGE, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function objectMove(callable $handler): void
    {
        \Omp\Server::on(Events::OBJECT_MOVE, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function playerCancelPlayerTextDrawSelection(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_CANCEL_PLAYER_TEXT_DRAW_SELECTION, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function playerCancelTextDrawSelection(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_CANCEL_TEXT_DRAW_SELECTION, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function playerClickGangZone(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_CLICK_GANG_ZONE, $handler);
    }

    /** @param callable(int, float, float, float): mixed $handler */
    public static function playerClickMap(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_CLICK_MAP, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function playerClickPlayer(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_CLICK_PLAYER, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function playerClickPlayerTextDraw(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_CLICK_PLAYER_TEXT_DRAW, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function playerClickTextDraw(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_CLICK_TEXT_DRAW, $handler);
    }

    /** @param callable(int, string): mixed $handler */
    public static function playerCommandText(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_COMMAND_TEXT, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function playerConnect(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_CONNECT, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function playerDeath(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_DEATH, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function playerDisconnect(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_DISCONNECT, $handler);
    }

    /** @param callable(int, bool, int, int, int, float, float, float, float, float, float, float, float, float): mixed $handler */
    public static function playerEditAttachedObject(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_EDIT_ATTACHED_OBJECT, $handler);
    }

    /** @param callable(int, int, int, float, float, float, float, float, float): mixed $handler */
    public static function playerEditObject(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_EDIT_OBJECT, $handler);
    }

    /** @param callable(int, int, int, float, float, float, float, float, float): mixed $handler */
    public static function playerEditPlayerObject(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_EDIT_PLAYER_OBJECT, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function playerEnterCheckpoint(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_ENTER_CHECKPOINT, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function playerEnterGangZone(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_ENTER_GANG_ZONE, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function playerEnterRaceCheckpoint(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_ENTER_RACE_CHECKPOINT, $handler);
    }

    /** @param callable(int, int, bool): mixed $handler */
    public static function playerEnterVehicle(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_ENTER_VEHICLE, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function playerExitVehicle(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_EXIT_VEHICLE, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function playerExitedMenu(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_EXITED_MENU, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function playerFinishedDownloading(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_FINISHED_DOWNLOADING, $handler);
    }

    /** @param callable(int, int, float, int, int): mixed $handler */
    public static function playerGiveDamage(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_GIVE_DAMAGE, $handler);
    }

    /** @param callable(int, int, float, int, int): mixed $handler */
    public static function playerGiveDamageActor(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_GIVE_DAMAGE_ACTOR, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function playerInteriorChange(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_INTERIOR_CHANGE, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function playerKeyStateChange(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_KEY_STATE_CHANGE, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function playerLeaveCheckpoint(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_LEAVE_CHECKPOINT, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function playerLeaveGangZone(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_LEAVE_GANG_ZONE, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function playerLeaveRaceCheckpoint(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_LEAVE_RACE_CHECKPOINT, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function playerObjectMove(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_OBJECT_MOVE, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function playerPickUpPickup(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_PICK_UP_PICKUP, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function playerRequestClass(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_REQUEST_CLASS, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function playerRequestDownload(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_REQUEST_DOWNLOAD, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function playerRequestSpawn(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_REQUEST_SPAWN, $handler);
    }

    /** @param callable(int, int, int, float, float, float): mixed $handler */
    public static function playerSelectObject(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_SELECT_OBJECT, $handler);
    }

    /** @param callable(int, int, int, float, float, float): mixed $handler */
    public static function playerSelectPlayerObject(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_SELECT_PLAYER_OBJECT, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function playerSelectedMenuRow(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_SELECTED_MENU_ROW, $handler);
    }

    /** @param callable(int, int, float, float, float): mixed $handler */
    public static function playerShotMissed(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_SHOT_MISSED, $handler);
    }

    /** @param callable(int, int, int, float, float, float): mixed $handler */
    public static function playerShotObject(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_SHOT_OBJECT, $handler);
    }

    /** @param callable(int, int, int, float, float, float): mixed $handler */
    public static function playerShotPlayer(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_SHOT_PLAYER, $handler);
    }

    /** @param callable(int, int, int, float, float, float): mixed $handler */
    public static function playerShotPlayerObject(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_SHOT_PLAYER_OBJECT, $handler);
    }

    /** @param callable(int, int, int, float, float, float): mixed $handler */
    public static function playerShotVehicle(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_SHOT_VEHICLE, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function playerSpawn(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_SPAWN, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function playerStateChange(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_STATE_CHANGE, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function playerStreamIn(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_STREAM_IN, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function playerStreamOut(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_STREAM_OUT, $handler);
    }

    /** @param callable(int, int, float, int, int): mixed $handler */
    public static function playerTakeDamage(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_TAKE_DAMAGE, $handler);
    }

    /** @param callable(int, string): mixed $handler */
    public static function playerText(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_TEXT, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function playerUpdate(callable $handler): void
    {
        \Omp\Server::on(Events::PLAYER_UPDATE, $handler);
    }

    /** @param callable(string, string, bool): mixed $handler */
    public static function rconLoginAttempt(callable $handler): void
    {
        \Omp\Server::on(Events::RCON_LOGIN_ATTEMPT, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function tick(callable $handler): void
    {
        \Omp\Server::on(Events::TICK, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function trailerUpdate(callable $handler): void
    {
        \Omp\Server::on(Events::TRAILER_UPDATE, $handler);
    }

    /** @param callable(int, int, int, float, float, float, float, float, float): mixed $handler */
    public static function unoccupiedVehicleUpdate(callable $handler): void
    {
        \Omp\Server::on(Events::UNOCCUPIED_VEHICLE_UPDATE, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function vehicleDamageStatusUpdate(callable $handler): void
    {
        \Omp\Server::on(Events::VEHICLE_DAMAGE_STATUS_UPDATE, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function vehicleDeath(callable $handler): void
    {
        \Omp\Server::on(Events::VEHICLE_DEATH, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function vehicleMod(callable $handler): void
    {
        \Omp\Server::on(Events::VEHICLE_MOD, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function vehiclePaintJob(callable $handler): void
    {
        \Omp\Server::on(Events::VEHICLE_PAINT_JOB, $handler);
    }

    /** @param callable(int, int, int, int): mixed $handler */
    public static function vehicleRespray(callable $handler): void
    {
        \Omp\Server::on(Events::VEHICLE_RESPRAY, $handler);
    }

    /** @param callable(int, int, int): mixed $handler */
    public static function vehicleSirenStateChange(callable $handler): void
    {
        \Omp\Server::on(Events::VEHICLE_SIREN_STATE_CHANGE, $handler);
    }

    /** @param callable(int): mixed $handler */
    public static function vehicleSpawn(callable $handler): void
    {
        \Omp\Server::on(Events::VEHICLE_SPAWN, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function vehicleStreamIn(callable $handler): void
    {
        \Omp\Server::on(Events::VEHICLE_STREAM_IN, $handler);
    }

    /** @param callable(int, int): mixed $handler */
    public static function vehicleStreamOut(callable $handler): void
    {
        \Omp\Server::on(Events::VEHICLE_STREAM_OUT, $handler);
    }

}
