// Code generated by tools/codegen. DO NOT EDIT.
package main

/*
#cgo CFLAGS: -I${SRCDIR}/../../third_party/omp-capi/lib/open.mp-capi/include
#include "ompcapi.h"
#include "events_generated.h"
*/
import "C"

import "unsafe"

//export OMPPHPDispatchGeneratedEvent
func OMPPHPDispatchGeneratedEvent(name *C.char, raw *C.struct_OMPPHPEventArg, count C.int, defaultResult C.bool) C.bool {
	component.Lock()
	active := component.runtime
	component.Unlock()
	fallback := bool(defaultResult)
	if active == nil {
		return C.bool(fallback)
	}
	cargs := unsafe.Slice(raw, int(count))
	arguments := make([]any, 0, len(cargs))
	for _, argument := range cargs {
		switch int(argument.kind) {
		case 1:
			arguments = append(arguments, int64(argument.integer))
		case 2:
			arguments = append(arguments, float64(argument.number))
		case 3:
			arguments = append(arguments, argument.integer != 0)
		case 4:
			arguments = append(arguments, C.GoStringN(argument.text, C.int(argument.length)))
		}
	}
	return C.bool(active.DispatchDefault(C.GoString(name), fallback, arguments...))
}
