// Code generated by tools/codegen. DO NOT EDIT.
#ifndef OMPPHP_EVENTS_GENERATED_H
#define OMPPHP_EVENTS_GENERATED_H

struct OMPPHPEventArg { int kind; int64_t integer; double number; const char* text; unsigned int length; };
extern struct OMPAPI_t ompphp_api;
extern int ompphp_player_id(void* player);
extern bool OMPPHPDispatchGeneratedEvent(char* name, struct OMPPHPEventArg* args, int count, bool default_result);

static bool ompphp_event_onActorStreamIn(struct EventArgs_onActorStreamIn* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].actor && *event->list[0].actor && ompphp_api.Actor.GetID ? ompphp_api.Actor.GetID(*event->list[0].actor) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].forPlayer && *event->list[0].forPlayer && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].forPlayer) : -1;
    return OMPPHPDispatchGeneratedEvent("ActorStreamIn", values, 2, true);
}

static bool ompphp_event_onActorStreamOut(struct EventArgs_onActorStreamOut* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].actor && *event->list[0].actor && ompphp_api.Actor.GetID ? ompphp_api.Actor.GetID(*event->list[0].actor) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].forPlayer && *event->list[0].forPlayer && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].forPlayer) : -1;
    return OMPPHPDispatchGeneratedEvent("ActorStreamOut", values, 2, true);
}

static bool ompphp_event_onClientCheckResponse(struct EventArgs_onClientCheckResponse* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[4] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].actionType ? *event->list[0].actionType : 0;
    values[2].kind = 1; values[2].integer = event->list[0].address ? *event->list[0].address : 0;
    values[3].kind = 1; values[3].integer = event->list[0].result ? *event->list[0].result : 0;
    return OMPPHPDispatchGeneratedEvent("ClientCheckResponse", values, 4, true);
}

static bool ompphp_event_onConsoleText(struct EventArgs_onConsoleText* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 4; if (event->list[0].command) { values[0].text = event->list[0].command->data; values[0].length = event->list[0].command->len; }
    values[1].kind = 4; if (event->list[0].parameters) { values[1].text = event->list[0].parameters->data; values[1].length = event->list[0].parameters->len; }
    return OMPPHPDispatchGeneratedEvent("ConsoleText", values, 2, true);
}

static bool ompphp_event_onDialogResponse(struct EventArgs_onDialogResponse* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[5] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].dialogId ? *event->list[0].dialogId : 0;
    values[2].kind = 1; values[2].integer = event->list[0].response ? *event->list[0].response : 0;
    values[3].kind = 1; values[3].integer = event->list[0].listItem ? *event->list[0].listItem : 0;
    values[4].kind = 4; if (event->list[0].inputText) { values[4].text = event->list[0].inputText->data; values[4].length = event->list[0].inputText->len; }
    return OMPPHPDispatchGeneratedEvent("DialogResponse", values, 5, true);
}

static bool ompphp_event_onEnterExitModShop(struct EventArgs_onEnterExitModShop* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].enterexit ? *event->list[0].enterexit : 0;
    values[2].kind = 1; values[2].integer = event->list[0].interiorId ? *event->list[0].interiorId : 0;
    return OMPPHPDispatchGeneratedEvent("EnterExitModShop", values, 3, true);
}

static bool ompphp_event_onIncomingConnection(struct EventArgs_onIncomingConnection* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 4; if (event->list[0].ipAddress) { values[1].text = event->list[0].ipAddress->data; values[1].length = event->list[0].ipAddress->len; }
    values[2].kind = 1; values[2].integer = event->list[0].port ? *event->list[0].port : 0;
    return OMPPHPDispatchGeneratedEvent("IncomingConnection", values, 3, true);
}

static bool ompphp_event_onNPCChangeNode(struct EventArgs_onNPCChangeNode* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].newNodeId ? *event->list[0].newNodeId : 0;
    values[2].kind = 1; values[2].integer = event->list[0].oldNodeId ? *event->list[0].oldNodeId : 0;
    return OMPPHPDispatchGeneratedEvent("NPCChangeNode", values, 3, false);
}

static bool ompphp_event_onNPCCreate(struct EventArgs_onNPCCreate* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    return OMPPHPDispatchGeneratedEvent("NPCCreate", values, 1, true);
}

static bool ompphp_event_onNPCDeath(struct EventArgs_onNPCDeath* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].killer && *event->list[0].killer && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].killer) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].reason ? *event->list[0].reason : 0;
    return OMPPHPDispatchGeneratedEvent("NPCDeath", values, 3, true);
}

static bool ompphp_event_onNPCDestroy(struct EventArgs_onNPCDestroy* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    return OMPPHPDispatchGeneratedEvent("NPCDestroy", values, 1, true);
}

static bool ompphp_event_onNPCFinishMove(struct EventArgs_onNPCFinishMove* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    return OMPPHPDispatchGeneratedEvent("NPCFinishMove", values, 1, true);
}

static bool ompphp_event_onNPCFinishMovePath(struct EventArgs_onNPCFinishMovePath* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].pathId ? *event->list[0].pathId : 0;
    return OMPPHPDispatchGeneratedEvent("NPCFinishMovePath", values, 2, true);
}

static bool ompphp_event_onNPCFinishMovePathPoint(struct EventArgs_onNPCFinishMovePathPoint* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].pathId ? *event->list[0].pathId : 0;
    values[2].kind = 1; values[2].integer = event->list[0].pointId ? *event->list[0].pointId : 0;
    return OMPPHPDispatchGeneratedEvent("NPCFinishMovePathPoint", values, 3, true);
}

static bool ompphp_event_onNPCFinishNode(struct EventArgs_onNPCFinishNode* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].nodeId ? *event->list[0].nodeId : 0;
    return OMPPHPDispatchGeneratedEvent("NPCFinishNode", values, 2, true);
}

static bool ompphp_event_onNPCFinishNodePoint(struct EventArgs_onNPCFinishNodePoint* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].nodeId ? *event->list[0].nodeId : 0;
    values[2].kind = 1; values[2].integer = event->list[0].pointId ? *event->list[0].pointId : 0;
    return OMPPHPDispatchGeneratedEvent("NPCFinishNodePoint", values, 3, true);
}

static bool ompphp_event_onNPCGiveDamage(struct EventArgs_onNPCGiveDamage* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[5] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].damaged && *event->list[0].damaged && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].damaged) : -1;
    values[2].kind = 2; values[2].number = event->list[0].damage ? *event->list[0].damage : 0;
    values[3].kind = 1; values[3].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[4].kind = 1; values[4].integer = event->list[0].bodyPart ? *event->list[0].bodyPart : 0;
    return OMPPHPDispatchGeneratedEvent("NPCGiveDamage", values, 5, true);
}

static bool ompphp_event_onNPCPlaybackEnd(struct EventArgs_onNPCPlaybackEnd* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].recordId ? *event->list[0].recordId : 0;
    return OMPPHPDispatchGeneratedEvent("NPCPlaybackEnd", values, 2, true);
}

static bool ompphp_event_onNPCPlaybackStart(struct EventArgs_onNPCPlaybackStart* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].recordId ? *event->list[0].recordId : 0;
    return OMPPHPDispatchGeneratedEvent("NPCPlaybackStart", values, 2, true);
}

static bool ompphp_event_onNPCRespawn(struct EventArgs_onNPCRespawn* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    return OMPPHPDispatchGeneratedEvent("NPCRespawn", values, 1, true);
}

static bool ompphp_event_onNPCShotMissed(struct EventArgs_onNPCShotMissed* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[5] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[2].kind = 2; values[2].number = event->list[0].offsetX ? *event->list[0].offsetX : 0;
    values[3].kind = 2; values[3].number = event->list[0].offsetY ? *event->list[0].offsetY : 0;
    values[4].kind = 2; values[4].number = event->list[0].offsetZ ? *event->list[0].offsetZ : 0;
    return OMPPHPDispatchGeneratedEvent("NPCShotMissed", values, 5, false);
}

static bool ompphp_event_onNPCShotNPC(struct EventArgs_onNPCShotNPC* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[6] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].npcTarget && *event->list[0].npcTarget && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npcTarget) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[3].kind = 2; values[3].number = event->list[0].offsetX ? *event->list[0].offsetX : 0;
    values[4].kind = 2; values[4].number = event->list[0].offsetY ? *event->list[0].offsetY : 0;
    values[5].kind = 2; values[5].number = event->list[0].offsetZ ? *event->list[0].offsetZ : 0;
    return OMPPHPDispatchGeneratedEvent("NPCShotNPC", values, 6, false);
}

static bool ompphp_event_onNPCShotObject(struct EventArgs_onNPCShotObject* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[6] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].object && *event->list[0].object && ompphp_api.Object.GetID ? ompphp_api.Object.GetID(*event->list[0].object) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[3].kind = 2; values[3].number = event->list[0].offsetX ? *event->list[0].offsetX : 0;
    values[4].kind = 2; values[4].number = event->list[0].offsetY ? *event->list[0].offsetY : 0;
    values[5].kind = 2; values[5].number = event->list[0].offsetZ ? *event->list[0].offsetZ : 0;
    return OMPPHPDispatchGeneratedEvent("NPCShotObject", values, 6, false);
}

static bool ompphp_event_onNPCShotPlayer(struct EventArgs_onNPCShotPlayer* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[6] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[3].kind = 2; values[3].number = event->list[0].offsetX ? *event->list[0].offsetX : 0;
    values[4].kind = 2; values[4].number = event->list[0].offsetY ? *event->list[0].offsetY : 0;
    values[5].kind = 2; values[5].number = event->list[0].offsetZ ? *event->list[0].offsetZ : 0;
    return OMPPHPDispatchGeneratedEvent("NPCShotPlayer", values, 6, false);
}

static bool ompphp_event_onNPCShotPlayerObject(struct EventArgs_onNPCShotPlayerObject* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[6] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    void* npcPlayer1 = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetPlayer ? ompphp_api.NPC.GetPlayer(*event->list[0].npc) : NULL;
    values[1].kind = 1; values[1].integer = event->list[0].playerObject && *event->list[0].playerObject && npcPlayer1 && ompphp_api.PlayerObject.GetID ? ompphp_api.PlayerObject.GetID(npcPlayer1, *event->list[0].playerObject) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[3].kind = 2; values[3].number = event->list[0].offsetX ? *event->list[0].offsetX : 0;
    values[4].kind = 2; values[4].number = event->list[0].offsetY ? *event->list[0].offsetY : 0;
    values[5].kind = 2; values[5].number = event->list[0].offsetZ ? *event->list[0].offsetZ : 0;
    return OMPPHPDispatchGeneratedEvent("NPCShotPlayerObject", values, 6, false);
}

static bool ompphp_event_onNPCShotVehicle(struct EventArgs_onNPCShotVehicle* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[6] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].vehicle && *event->list[0].vehicle && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].vehicle) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[3].kind = 2; values[3].number = event->list[0].offsetX ? *event->list[0].offsetX : 0;
    values[4].kind = 2; values[4].number = event->list[0].offsetY ? *event->list[0].offsetY : 0;
    values[5].kind = 2; values[5].number = event->list[0].offsetZ ? *event->list[0].offsetZ : 0;
    return OMPPHPDispatchGeneratedEvent("NPCShotVehicle", values, 6, false);
}

static bool ompphp_event_onNPCSpawn(struct EventArgs_onNPCSpawn* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    return OMPPHPDispatchGeneratedEvent("NPCSpawn", values, 1, true);
}

static bool ompphp_event_onNPCTakeDamage(struct EventArgs_onNPCTakeDamage* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[5] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].damager && *event->list[0].damager && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].damager) : -1;
    values[2].kind = 2; values[2].number = event->list[0].damage ? *event->list[0].damage : 0;
    values[3].kind = 1; values[3].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[4].kind = 1; values[4].integer = event->list[0].bodyPart ? *event->list[0].bodyPart : 0;
    return OMPPHPDispatchGeneratedEvent("NPCTakeDamage", values, 5, false);
}

static bool ompphp_event_onNPCWeaponStateChange(struct EventArgs_onNPCWeaponStateChange* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetID ? ompphp_api.NPC.GetID(*event->list[0].npc) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].newState ? *event->list[0].newState : 0;
    values[2].kind = 1; values[2].integer = event->list[0].oldState ? *event->list[0].oldState : 0;
    return OMPPHPDispatchGeneratedEvent("NPCWeaponStateChange", values, 3, true);
}

static bool ompphp_event_onObjectMove(struct EventArgs_onObjectMove* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].object && *event->list[0].object && ompphp_api.Object.GetID ? ompphp_api.Object.GetID(*event->list[0].object) : -1;
    return OMPPHPDispatchGeneratedEvent("ObjectMove", values, 1, true);
}

static bool ompphp_event_onPlayerCancelPlayerTextDrawSelection(struct EventArgs_onPlayerCancelPlayerTextDrawSelection* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerCancelPlayerTextDrawSelection", values, 1, true);
}

static bool ompphp_event_onPlayerCancelTextDrawSelection(struct EventArgs_onPlayerCancelTextDrawSelection* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerCancelTextDrawSelection", values, 1, true);
}

static bool ompphp_event_onPlayerClickGangZone(struct EventArgs_onPlayerClickGangZone* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].zone && *event->list[0].zone && ompphp_api.GangZone.GetID ? ompphp_api.GangZone.GetID(*event->list[0].zone) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerClickGangZone", values, 2, true);
}

static bool ompphp_event_onPlayerClickMap(struct EventArgs_onPlayerClickMap* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[4] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 2; values[1].number = event->list[0].x ? *event->list[0].x : 0;
    values[2].kind = 2; values[2].number = event->list[0].y ? *event->list[0].y : 0;
    values[3].kind = 2; values[3].number = event->list[0].z ? *event->list[0].z : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerClickMap", values, 4, true);
}

static bool ompphp_event_onPlayerClickPlayer(struct EventArgs_onPlayerClickPlayer* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].clicked && *event->list[0].clicked && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].clicked) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].source ? *event->list[0].source : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerClickPlayer", values, 3, true);
}

static bool ompphp_event_onPlayerClickPlayerTextDraw(struct EventArgs_onPlayerClickPlayerTextDraw* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].textdraw && *event->list[0].textdraw && event->list[0].player && *event->list[0].player && ompphp_api.PlayerTextDraw.GetID ? ompphp_api.PlayerTextDraw.GetID(*event->list[0].player, *event->list[0].textdraw) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerClickPlayerTextDraw", values, 2, true);
}

static bool ompphp_event_onPlayerClickTextDraw(struct EventArgs_onPlayerClickTextDraw* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].textdraw && *event->list[0].textdraw && ompphp_api.TextDraw.GetID ? ompphp_api.TextDraw.GetID(*event->list[0].textdraw) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerClickTextDraw", values, 2, true);
}

static bool ompphp_event_onPlayerCommandText(struct EventArgs_onPlayerCommandText* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 4; if (event->list[0].command) { values[1].text = event->list[0].command->data; values[1].length = event->list[0].command->len; }
    return OMPPHPDispatchGeneratedEvent("PlayerCommandText", values, 2, true);
}

static bool ompphp_event_onPlayerConnect(struct EventArgs_onPlayerConnect* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerConnect", values, 1, true);
}

static bool ompphp_event_onPlayerDeath(struct EventArgs_onPlayerDeath* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].killer && *event->list[0].killer && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].killer) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].reason ? *event->list[0].reason : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerDeath", values, 3, true);
}

static bool ompphp_event_onPlayerDisconnect(struct EventArgs_onPlayerDisconnect* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].reason ? *event->list[0].reason : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerDisconnect", values, 2, true);
}

static bool ompphp_event_onPlayerEditAttachedObject(struct EventArgs_onPlayerEditAttachedObject* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[14] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 3; values[1].integer = event->list[0].saved && *event->list[0].saved;
    values[2].kind = 1; values[2].integer = event->list[0].index ? *event->list[0].index : 0;
    values[3].kind = 1; values[3].integer = event->list[0].model ? *event->list[0].model : 0;
    values[4].kind = 1; values[4].integer = event->list[0].bone ? *event->list[0].bone : 0;
    values[5].kind = 2; values[5].number = event->list[0].offsetX ? *event->list[0].offsetX : 0;
    values[6].kind = 2; values[6].number = event->list[0].offsetY ? *event->list[0].offsetY : 0;
    values[7].kind = 2; values[7].number = event->list[0].offsetZ ? *event->list[0].offsetZ : 0;
    values[8].kind = 2; values[8].number = event->list[0].rotationX ? *event->list[0].rotationX : 0;
    values[9].kind = 2; values[9].number = event->list[0].rotationY ? *event->list[0].rotationY : 0;
    values[10].kind = 2; values[10].number = event->list[0].rotationZ ? *event->list[0].rotationZ : 0;
    values[11].kind = 2; values[11].number = event->list[0].scaleX ? *event->list[0].scaleX : 0;
    values[12].kind = 2; values[12].number = event->list[0].scaleY ? *event->list[0].scaleY : 0;
    values[13].kind = 2; values[13].number = event->list[0].scaleZ ? *event->list[0].scaleZ : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerEditAttachedObject", values, 14, true);
}

static bool ompphp_event_onPlayerEditObject(struct EventArgs_onPlayerEditObject* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[9] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].object && *event->list[0].object && ompphp_api.Object.GetID ? ompphp_api.Object.GetID(*event->list[0].object) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].response ? *event->list[0].response : 0;
    values[3].kind = 2; values[3].number = event->list[0].offsetX ? *event->list[0].offsetX : 0;
    values[4].kind = 2; values[4].number = event->list[0].offsetY ? *event->list[0].offsetY : 0;
    values[5].kind = 2; values[5].number = event->list[0].offsetZ ? *event->list[0].offsetZ : 0;
    values[6].kind = 2; values[6].number = event->list[0].rotationX ? *event->list[0].rotationX : 0;
    values[7].kind = 2; values[7].number = event->list[0].rotationY ? *event->list[0].rotationY : 0;
    values[8].kind = 2; values[8].number = event->list[0].rotationZ ? *event->list[0].rotationZ : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerEditObject", values, 9, true);
}

static bool ompphp_event_onPlayerEditPlayerObject(struct EventArgs_onPlayerEditPlayerObject* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[9] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].object && *event->list[0].object && event->list[0].player && *event->list[0].player && ompphp_api.PlayerObject.GetID ? ompphp_api.PlayerObject.GetID(*event->list[0].player, *event->list[0].object) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].response ? *event->list[0].response : 0;
    values[3].kind = 2; values[3].number = event->list[0].offsetX ? *event->list[0].offsetX : 0;
    values[4].kind = 2; values[4].number = event->list[0].offsetY ? *event->list[0].offsetY : 0;
    values[5].kind = 2; values[5].number = event->list[0].offsetZ ? *event->list[0].offsetZ : 0;
    values[6].kind = 2; values[6].number = event->list[0].rotationX ? *event->list[0].rotationX : 0;
    values[7].kind = 2; values[7].number = event->list[0].rotationY ? *event->list[0].rotationY : 0;
    values[8].kind = 2; values[8].number = event->list[0].rotationZ ? *event->list[0].rotationZ : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerEditPlayerObject", values, 9, true);
}

static bool ompphp_event_onPlayerEnterCheckpoint(struct EventArgs_onPlayerEnterCheckpoint* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerEnterCheckpoint", values, 1, true);
}

static bool ompphp_event_onPlayerEnterGangZone(struct EventArgs_onPlayerEnterGangZone* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].zone && *event->list[0].zone && ompphp_api.GangZone.GetID ? ompphp_api.GangZone.GetID(*event->list[0].zone) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerEnterGangZone", values, 2, true);
}

static bool ompphp_event_onPlayerEnterRaceCheckpoint(struct EventArgs_onPlayerEnterRaceCheckpoint* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerEnterRaceCheckpoint", values, 1, true);
}

static bool ompphp_event_onPlayerEnterVehicle(struct EventArgs_onPlayerEnterVehicle* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].vehicle && *event->list[0].vehicle && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].vehicle) : -1;
    values[2].kind = 3; values[2].integer = event->list[0].passenger && *event->list[0].passenger;
    return OMPPHPDispatchGeneratedEvent("PlayerEnterVehicle", values, 3, true);
}

static bool ompphp_event_onPlayerExitVehicle(struct EventArgs_onPlayerExitVehicle* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].vehicle && *event->list[0].vehicle && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].vehicle) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerExitVehicle", values, 2, true);
}

static bool ompphp_event_onPlayerExitedMenu(struct EventArgs_onPlayerExitedMenu* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerExitedMenu", values, 1, true);
}

static bool ompphp_event_onPlayerFinishedDownloading(struct EventArgs_onPlayerFinishedDownloading* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].vw ? *event->list[0].vw : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerFinishedDownloading", values, 2, true);
}

static bool ompphp_event_onPlayerGiveDamage(struct EventArgs_onPlayerGiveDamage* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[5] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].to && *event->list[0].to && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].to) : -1;
    values[2].kind = 2; values[2].number = event->list[0].amount ? *event->list[0].amount : 0;
    values[3].kind = 1; values[3].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[4].kind = 1; values[4].integer = event->list[0].bodypart ? *event->list[0].bodypart : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerGiveDamage", values, 5, true);
}

static bool ompphp_event_onPlayerGiveDamageActor(struct EventArgs_onPlayerGiveDamageActor* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[5] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].actor && *event->list[0].actor && ompphp_api.Actor.GetID ? ompphp_api.Actor.GetID(*event->list[0].actor) : -1;
    values[2].kind = 2; values[2].number = event->list[0].amount ? *event->list[0].amount : 0;
    values[3].kind = 1; values[3].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[4].kind = 1; values[4].integer = event->list[0].part ? *event->list[0].part : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerGiveDamageActor", values, 5, true);
}

static bool ompphp_event_onPlayerInteriorChange(struct EventArgs_onPlayerInteriorChange* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].newInterior ? *event->list[0].newInterior : 0;
    values[2].kind = 1; values[2].integer = event->list[0].oldInterior ? *event->list[0].oldInterior : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerInteriorChange", values, 3, true);
}

static bool ompphp_event_onPlayerKeyStateChange(struct EventArgs_onPlayerKeyStateChange* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].newKeys ? *event->list[0].newKeys : 0;
    values[2].kind = 1; values[2].integer = event->list[0].oldKeys ? *event->list[0].oldKeys : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerKeyStateChange", values, 3, true);
}

static bool ompphp_event_onPlayerLeaveCheckpoint(struct EventArgs_onPlayerLeaveCheckpoint* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerLeaveCheckpoint", values, 1, true);
}

static bool ompphp_event_onPlayerLeaveGangZone(struct EventArgs_onPlayerLeaveGangZone* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].zone && *event->list[0].zone && ompphp_api.GangZone.GetID ? ompphp_api.GangZone.GetID(*event->list[0].zone) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerLeaveGangZone", values, 2, true);
}

static bool ompphp_event_onPlayerLeaveRaceCheckpoint(struct EventArgs_onPlayerLeaveRaceCheckpoint* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerLeaveRaceCheckpoint", values, 1, true);
}

static bool ompphp_event_onPlayerObjectMove(struct EventArgs_onPlayerObjectMove* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].object && *event->list[0].object && event->list[0].player && *event->list[0].player && ompphp_api.PlayerObject.GetID ? ompphp_api.PlayerObject.GetID(*event->list[0].player, *event->list[0].object) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerObjectMove", values, 2, true);
}

static bool ompphp_event_onPlayerPickUpPickup(struct EventArgs_onPlayerPickUpPickup* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].pickup && *event->list[0].pickup && ompphp_api.Pickup.GetID ? ompphp_api.Pickup.GetID(*event->list[0].pickup) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerPickUpPickup", values, 2, true);
}

static bool ompphp_event_onPlayerRequestClass(struct EventArgs_onPlayerRequestClass* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].classId ? *event->list[0].classId : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerRequestClass", values, 2, false);
}

static bool ompphp_event_onPlayerRequestDownload(struct EventArgs_onPlayerRequestDownload* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].type ? *event->list[0].type : 0;
    values[2].kind = 1; values[2].integer = event->list[0].checksum ? *event->list[0].checksum : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerRequestDownload", values, 3, true);
}

static bool ompphp_event_onPlayerRequestSpawn(struct EventArgs_onPlayerRequestSpawn* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerRequestSpawn", values, 1, false);
}

static bool ompphp_event_onPlayerSelectObject(struct EventArgs_onPlayerSelectObject* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[6] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].object && *event->list[0].object && ompphp_api.Object.GetID ? ompphp_api.Object.GetID(*event->list[0].object) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].model ? *event->list[0].model : 0;
    values[3].kind = 2; values[3].number = event->list[0].x ? *event->list[0].x : 0;
    values[4].kind = 2; values[4].number = event->list[0].y ? *event->list[0].y : 0;
    values[5].kind = 2; values[5].number = event->list[0].z ? *event->list[0].z : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerSelectObject", values, 6, true);
}

static bool ompphp_event_onPlayerSelectPlayerObject(struct EventArgs_onPlayerSelectPlayerObject* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[6] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].object && *event->list[0].object && event->list[0].player && *event->list[0].player && ompphp_api.PlayerObject.GetID ? ompphp_api.PlayerObject.GetID(*event->list[0].player, *event->list[0].object) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].model ? *event->list[0].model : 0;
    values[3].kind = 2; values[3].number = event->list[0].x ? *event->list[0].x : 0;
    values[4].kind = 2; values[4].number = event->list[0].y ? *event->list[0].y : 0;
    values[5].kind = 2; values[5].number = event->list[0].z ? *event->list[0].z : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerSelectPlayerObject", values, 6, true);
}

static bool ompphp_event_onPlayerSelectedMenuRow(struct EventArgs_onPlayerSelectedMenuRow* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].row ? *event->list[0].row : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerSelectedMenuRow", values, 2, true);
}

static bool ompphp_event_onPlayerShotMissed(struct EventArgs_onPlayerShotMissed* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[5] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[2].kind = 2; values[2].number = event->list[0].x ? *event->list[0].x : 0;
    values[3].kind = 2; values[3].number = event->list[0].y ? *event->list[0].y : 0;
    values[4].kind = 2; values[4].number = event->list[0].z ? *event->list[0].z : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerShotMissed", values, 5, false);
}

static bool ompphp_event_onPlayerShotObject(struct EventArgs_onPlayerShotObject* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[6] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].target && *event->list[0].target && ompphp_api.Object.GetID ? ompphp_api.Object.GetID(*event->list[0].target) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[3].kind = 2; values[3].number = event->list[0].x ? *event->list[0].x : 0;
    values[4].kind = 2; values[4].number = event->list[0].y ? *event->list[0].y : 0;
    values[5].kind = 2; values[5].number = event->list[0].z ? *event->list[0].z : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerShotObject", values, 6, false);
}

static bool ompphp_event_onPlayerShotPlayer(struct EventArgs_onPlayerShotPlayer* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[6] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].target && *event->list[0].target && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].target) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[3].kind = 2; values[3].number = event->list[0].x ? *event->list[0].x : 0;
    values[4].kind = 2; values[4].number = event->list[0].y ? *event->list[0].y : 0;
    values[5].kind = 2; values[5].number = event->list[0].z ? *event->list[0].z : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerShotPlayer", values, 6, false);
}

static bool ompphp_event_onPlayerShotPlayerObject(struct EventArgs_onPlayerShotPlayerObject* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[6] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].target && *event->list[0].target && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].target) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[3].kind = 2; values[3].number = event->list[0].x ? *event->list[0].x : 0;
    values[4].kind = 2; values[4].number = event->list[0].y ? *event->list[0].y : 0;
    values[5].kind = 2; values[5].number = event->list[0].z ? *event->list[0].z : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerShotPlayerObject", values, 6, false);
}

static bool ompphp_event_onPlayerShotVehicle(struct EventArgs_onPlayerShotVehicle* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[6] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].target && *event->list[0].target && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].target) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[3].kind = 2; values[3].number = event->list[0].x ? *event->list[0].x : 0;
    values[4].kind = 2; values[4].number = event->list[0].y ? *event->list[0].y : 0;
    values[5].kind = 2; values[5].number = event->list[0].z ? *event->list[0].z : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerShotVehicle", values, 6, false);
}

static bool ompphp_event_onPlayerSpawn(struct EventArgs_onPlayerSpawn* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerSpawn", values, 1, true);
}

static bool ompphp_event_onPlayerStateChange(struct EventArgs_onPlayerStateChange* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].newState ? *event->list[0].newState : 0;
    values[2].kind = 1; values[2].integer = event->list[0].oldState ? *event->list[0].oldState : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerStateChange", values, 3, true);
}

static bool ompphp_event_onPlayerStreamIn(struct EventArgs_onPlayerStreamIn* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].forPlayer && *event->list[0].forPlayer && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].forPlayer) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerStreamIn", values, 2, true);
}

static bool ompphp_event_onPlayerStreamOut(struct EventArgs_onPlayerStreamOut* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].forPlayer && *event->list[0].forPlayer && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].forPlayer) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerStreamOut", values, 2, true);
}

static bool ompphp_event_onPlayerTakeDamage(struct EventArgs_onPlayerTakeDamage* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[5] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].from && *event->list[0].from && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].from) : -1;
    values[2].kind = 2; values[2].number = event->list[0].amount ? *event->list[0].amount : 0;
    values[3].kind = 1; values[3].integer = event->list[0].weapon ? *event->list[0].weapon : 0;
    values[4].kind = 1; values[4].integer = event->list[0].bodypart ? *event->list[0].bodypart : 0;
    return OMPPHPDispatchGeneratedEvent("PlayerTakeDamage", values, 5, true);
}

static bool ompphp_event_onPlayerText(struct EventArgs_onPlayerText* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 4; if (event->list[0].text) { values[1].text = event->list[0].text->data; values[1].length = event->list[0].text->len; }
    return OMPPHPDispatchGeneratedEvent("PlayerText", values, 2, false);
}

static bool ompphp_event_onPlayerUpdate(struct EventArgs_onPlayerUpdate* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("PlayerUpdate", values, 1, false);
}

static bool ompphp_event_onRconLoginAttempt(struct EventArgs_onRconLoginAttempt* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 4; if (event->list[0].address) { values[0].text = event->list[0].address->data; values[0].length = event->list[0].address->len; }
    values[1].kind = 4; if (event->list[0].password) { values[1].text = event->list[0].password->data; values[1].length = event->list[0].password->len; }
    values[2].kind = 3; values[2].integer = event->list[0].success && *event->list[0].success;
    return OMPPHPDispatchGeneratedEvent("RconLoginAttempt", values, 3, true);
}

static bool ompphp_event_onTick(struct EventArgs_onTick* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].elapsed ? *event->list[0].elapsed : 0;
    return OMPPHPDispatchGeneratedEvent("Tick", values, 1, true);
}

static bool ompphp_event_onTrailerUpdate(struct EventArgs_onTrailerUpdate* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].trailer && *event->list[0].trailer && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].trailer) : -1;
    return OMPPHPDispatchGeneratedEvent("TrailerUpdate", values, 2, false);
}

static bool ompphp_event_onUnoccupiedVehicleUpdate(struct EventArgs_onUnoccupiedVehicleUpdate* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[9] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].vehicle && *event->list[0].vehicle && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].vehicle) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].seat ? *event->list[0].seat : 0;
    values[3].kind = 2; values[3].number = event->list[0].posX ? *event->list[0].posX : 0;
    values[4].kind = 2; values[4].number = event->list[0].posY ? *event->list[0].posY : 0;
    values[5].kind = 2; values[5].number = event->list[0].posZ ? *event->list[0].posZ : 0;
    values[6].kind = 2; values[6].number = event->list[0].velocityX ? *event->list[0].velocityX : 0;
    values[7].kind = 2; values[7].number = event->list[0].velocityY ? *event->list[0].velocityY : 0;
    values[8].kind = 2; values[8].number = event->list[0].velocityZ ? *event->list[0].velocityZ : 0;
    return OMPPHPDispatchGeneratedEvent("UnoccupiedVehicleUpdate", values, 9, false);
}

static bool ompphp_event_onVehicleDamageStatusUpdate(struct EventArgs_onVehicleDamageStatusUpdate* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].vehicle && *event->list[0].vehicle && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].vehicle) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("VehicleDamageStatusUpdate", values, 2, true);
}

static bool ompphp_event_onVehicleDeath(struct EventArgs_onVehicleDeath* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].vehicle && *event->list[0].vehicle && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].vehicle) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("VehicleDeath", values, 2, true);
}

static bool ompphp_event_onVehicleMod(struct EventArgs_onVehicleMod* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].vehicle && *event->list[0].vehicle && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].vehicle) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].component ? *event->list[0].component : 0;
    return OMPPHPDispatchGeneratedEvent("VehicleMod", values, 3, false);
}

static bool ompphp_event_onVehiclePaintJob(struct EventArgs_onVehiclePaintJob* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].vehicle && *event->list[0].vehicle && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].vehicle) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].paintJob ? *event->list[0].paintJob : 0;
    return OMPPHPDispatchGeneratedEvent("VehiclePaintJob", values, 3, false);
}

static bool ompphp_event_onVehicleRespray(struct EventArgs_onVehicleRespray* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[4] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].vehicle && *event->list[0].vehicle && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].vehicle) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].color1 ? *event->list[0].color1 : 0;
    values[3].kind = 1; values[3].integer = event->list[0].color2 ? *event->list[0].color2 : 0;
    return OMPPHPDispatchGeneratedEvent("VehicleRespray", values, 4, false);
}

static bool ompphp_event_onVehicleSirenStateChange(struct EventArgs_onVehicleSirenStateChange* event) {
    if (!event || event->size < 1 || !event->list) return false;
    struct OMPPHPEventArg values[3] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].vehicle && *event->list[0].vehicle && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].vehicle) : -1;
    values[2].kind = 1; values[2].integer = event->list[0].sirenState ? *event->list[0].sirenState : 0;
    return OMPPHPDispatchGeneratedEvent("VehicleSirenStateChange", values, 3, false);
}

static bool ompphp_event_onVehicleSpawn(struct EventArgs_onVehicleSpawn* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[1] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].vehicle && *event->list[0].vehicle && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].vehicle) : -1;
    return OMPPHPDispatchGeneratedEvent("VehicleSpawn", values, 1, true);
}

static bool ompphp_event_onVehicleStreamIn(struct EventArgs_onVehicleStreamIn* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].vehicle && *event->list[0].vehicle && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].vehicle) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("VehicleStreamIn", values, 2, true);
}

static bool ompphp_event_onVehicleStreamOut(struct EventArgs_onVehicleStreamOut* event) {
    if (!event || event->size < 1 || !event->list) return true;
    struct OMPPHPEventArg values[2] = {0};
    values[0].kind = 1; values[0].integer = event->list[0].vehicle && *event->list[0].vehicle && ompphp_api.Vehicle.GetID ? ompphp_api.Vehicle.GetID(*event->list[0].vehicle) : -1;
    values[1].kind = 1; values[1].integer = event->list[0].player && *event->list[0].player && ompphp_api.Player.GetID ? ompphp_api.Player.GetID(*event->list[0].player) : -1;
    return OMPPHPDispatchGeneratedEvent("VehicleStreamOut", values, 2, true);
}

static bool ompphp_register_generated_events(void) {
    bool ok = true;
    ok = ompphp_api.Event.AddHandler("onActorStreamIn", EventPriorityType_Default, (void*)ompphp_event_onActorStreamIn) && ok;
    ok = ompphp_api.Event.AddHandler("onActorStreamOut", EventPriorityType_Default, (void*)ompphp_event_onActorStreamOut) && ok;
    ok = ompphp_api.Event.AddHandler("onClientCheckResponse", EventPriorityType_Default, (void*)ompphp_event_onClientCheckResponse) && ok;
    ok = ompphp_api.Event.AddHandler("onConsoleText", EventPriorityType_Default, (void*)ompphp_event_onConsoleText) && ok;
    ok = ompphp_api.Event.AddHandler("onDialogResponse", EventPriorityType_Default, (void*)ompphp_event_onDialogResponse) && ok;
    ok = ompphp_api.Event.AddHandler("onEnterExitModShop", EventPriorityType_Default, (void*)ompphp_event_onEnterExitModShop) && ok;
    ok = ompphp_api.Event.AddHandler("onIncomingConnection", EventPriorityType_Default, (void*)ompphp_event_onIncomingConnection) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCChangeNode", EventPriorityType_Default, (void*)ompphp_event_onNPCChangeNode) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCCreate", EventPriorityType_Default, (void*)ompphp_event_onNPCCreate) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCDeath", EventPriorityType_Default, (void*)ompphp_event_onNPCDeath) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCDestroy", EventPriorityType_Default, (void*)ompphp_event_onNPCDestroy) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCFinishMove", EventPriorityType_Default, (void*)ompphp_event_onNPCFinishMove) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCFinishMovePath", EventPriorityType_Default, (void*)ompphp_event_onNPCFinishMovePath) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCFinishMovePathPoint", EventPriorityType_Default, (void*)ompphp_event_onNPCFinishMovePathPoint) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCFinishNode", EventPriorityType_Default, (void*)ompphp_event_onNPCFinishNode) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCFinishNodePoint", EventPriorityType_Default, (void*)ompphp_event_onNPCFinishNodePoint) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCGiveDamage", EventPriorityType_Default, (void*)ompphp_event_onNPCGiveDamage) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCPlaybackEnd", EventPriorityType_Default, (void*)ompphp_event_onNPCPlaybackEnd) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCPlaybackStart", EventPriorityType_Default, (void*)ompphp_event_onNPCPlaybackStart) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCRespawn", EventPriorityType_Default, (void*)ompphp_event_onNPCRespawn) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCShotMissed", EventPriorityType_Default, (void*)ompphp_event_onNPCShotMissed) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCShotNPC", EventPriorityType_Default, (void*)ompphp_event_onNPCShotNPC) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCShotObject", EventPriorityType_Default, (void*)ompphp_event_onNPCShotObject) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCShotPlayer", EventPriorityType_Default, (void*)ompphp_event_onNPCShotPlayer) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCShotPlayerObject", EventPriorityType_Default, (void*)ompphp_event_onNPCShotPlayerObject) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCShotVehicle", EventPriorityType_Default, (void*)ompphp_event_onNPCShotVehicle) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCSpawn", EventPriorityType_Default, (void*)ompphp_event_onNPCSpawn) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCTakeDamage", EventPriorityType_Default, (void*)ompphp_event_onNPCTakeDamage) && ok;
    ok = ompphp_api.Event.AddHandler("onNPCWeaponStateChange", EventPriorityType_Default, (void*)ompphp_event_onNPCWeaponStateChange) && ok;
    ok = ompphp_api.Event.AddHandler("onObjectMove", EventPriorityType_Default, (void*)ompphp_event_onObjectMove) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerCancelPlayerTextDrawSelection", EventPriorityType_Default, (void*)ompphp_event_onPlayerCancelPlayerTextDrawSelection) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerCancelTextDrawSelection", EventPriorityType_Default, (void*)ompphp_event_onPlayerCancelTextDrawSelection) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerClickGangZone", EventPriorityType_Default, (void*)ompphp_event_onPlayerClickGangZone) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerClickMap", EventPriorityType_Default, (void*)ompphp_event_onPlayerClickMap) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerClickPlayer", EventPriorityType_Default, (void*)ompphp_event_onPlayerClickPlayer) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerClickPlayerTextDraw", EventPriorityType_Default, (void*)ompphp_event_onPlayerClickPlayerTextDraw) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerClickTextDraw", EventPriorityType_Default, (void*)ompphp_event_onPlayerClickTextDraw) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerCommandText", EventPriorityType_Default, (void*)ompphp_event_onPlayerCommandText) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerConnect", EventPriorityType_Default, (void*)ompphp_event_onPlayerConnect) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerDeath", EventPriorityType_Default, (void*)ompphp_event_onPlayerDeath) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerDisconnect", EventPriorityType_Default, (void*)ompphp_event_onPlayerDisconnect) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerEditAttachedObject", EventPriorityType_Default, (void*)ompphp_event_onPlayerEditAttachedObject) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerEditObject", EventPriorityType_Default, (void*)ompphp_event_onPlayerEditObject) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerEditPlayerObject", EventPriorityType_Default, (void*)ompphp_event_onPlayerEditPlayerObject) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerEnterCheckpoint", EventPriorityType_Default, (void*)ompphp_event_onPlayerEnterCheckpoint) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerEnterGangZone", EventPriorityType_Default, (void*)ompphp_event_onPlayerEnterGangZone) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerEnterRaceCheckpoint", EventPriorityType_Default, (void*)ompphp_event_onPlayerEnterRaceCheckpoint) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerEnterVehicle", EventPriorityType_Default, (void*)ompphp_event_onPlayerEnterVehicle) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerExitVehicle", EventPriorityType_Default, (void*)ompphp_event_onPlayerExitVehicle) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerExitedMenu", EventPriorityType_Default, (void*)ompphp_event_onPlayerExitedMenu) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerFinishedDownloading", EventPriorityType_Default, (void*)ompphp_event_onPlayerFinishedDownloading) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerGiveDamage", EventPriorityType_Default, (void*)ompphp_event_onPlayerGiveDamage) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerGiveDamageActor", EventPriorityType_Default, (void*)ompphp_event_onPlayerGiveDamageActor) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerInteriorChange", EventPriorityType_Default, (void*)ompphp_event_onPlayerInteriorChange) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerKeyStateChange", EventPriorityType_Default, (void*)ompphp_event_onPlayerKeyStateChange) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerLeaveCheckpoint", EventPriorityType_Default, (void*)ompphp_event_onPlayerLeaveCheckpoint) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerLeaveGangZone", EventPriorityType_Default, (void*)ompphp_event_onPlayerLeaveGangZone) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerLeaveRaceCheckpoint", EventPriorityType_Default, (void*)ompphp_event_onPlayerLeaveRaceCheckpoint) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerObjectMove", EventPriorityType_Default, (void*)ompphp_event_onPlayerObjectMove) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerPickUpPickup", EventPriorityType_Default, (void*)ompphp_event_onPlayerPickUpPickup) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerRequestClass", EventPriorityType_Default, (void*)ompphp_event_onPlayerRequestClass) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerRequestDownload", EventPriorityType_Default, (void*)ompphp_event_onPlayerRequestDownload) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerRequestSpawn", EventPriorityType_Default, (void*)ompphp_event_onPlayerRequestSpawn) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerSelectObject", EventPriorityType_Default, (void*)ompphp_event_onPlayerSelectObject) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerSelectPlayerObject", EventPriorityType_Default, (void*)ompphp_event_onPlayerSelectPlayerObject) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerSelectedMenuRow", EventPriorityType_Default, (void*)ompphp_event_onPlayerSelectedMenuRow) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerShotMissed", EventPriorityType_Default, (void*)ompphp_event_onPlayerShotMissed) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerShotObject", EventPriorityType_Default, (void*)ompphp_event_onPlayerShotObject) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerShotPlayer", EventPriorityType_Default, (void*)ompphp_event_onPlayerShotPlayer) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerShotPlayerObject", EventPriorityType_Default, (void*)ompphp_event_onPlayerShotPlayerObject) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerShotVehicle", EventPriorityType_Default, (void*)ompphp_event_onPlayerShotVehicle) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerSpawn", EventPriorityType_Default, (void*)ompphp_event_onPlayerSpawn) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerStateChange", EventPriorityType_Default, (void*)ompphp_event_onPlayerStateChange) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerStreamIn", EventPriorityType_Default, (void*)ompphp_event_onPlayerStreamIn) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerStreamOut", EventPriorityType_Default, (void*)ompphp_event_onPlayerStreamOut) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerTakeDamage", EventPriorityType_Default, (void*)ompphp_event_onPlayerTakeDamage) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerText", EventPriorityType_Default, (void*)ompphp_event_onPlayerText) && ok;
    ok = ompphp_api.Event.AddHandler("onPlayerUpdate", EventPriorityType_Default, (void*)ompphp_event_onPlayerUpdate) && ok;
    ok = ompphp_api.Event.AddHandler("onRconLoginAttempt", EventPriorityType_Default, (void*)ompphp_event_onRconLoginAttempt) && ok;
    ok = ompphp_api.Event.AddHandler("onTick", EventPriorityType_Default, (void*)ompphp_event_onTick) && ok;
    ok = ompphp_api.Event.AddHandler("onTrailerUpdate", EventPriorityType_Default, (void*)ompphp_event_onTrailerUpdate) && ok;
    ok = ompphp_api.Event.AddHandler("onUnoccupiedVehicleUpdate", EventPriorityType_Default, (void*)ompphp_event_onUnoccupiedVehicleUpdate) && ok;
    ok = ompphp_api.Event.AddHandler("onVehicleDamageStatusUpdate", EventPriorityType_Default, (void*)ompphp_event_onVehicleDamageStatusUpdate) && ok;
    ok = ompphp_api.Event.AddHandler("onVehicleDeath", EventPriorityType_Default, (void*)ompphp_event_onVehicleDeath) && ok;
    ok = ompphp_api.Event.AddHandler("onVehicleMod", EventPriorityType_Default, (void*)ompphp_event_onVehicleMod) && ok;
    ok = ompphp_api.Event.AddHandler("onVehiclePaintJob", EventPriorityType_Default, (void*)ompphp_event_onVehiclePaintJob) && ok;
    ok = ompphp_api.Event.AddHandler("onVehicleRespray", EventPriorityType_Default, (void*)ompphp_event_onVehicleRespray) && ok;
    ok = ompphp_api.Event.AddHandler("onVehicleSirenStateChange", EventPriorityType_Default, (void*)ompphp_event_onVehicleSirenStateChange) && ok;
    ok = ompphp_api.Event.AddHandler("onVehicleSpawn", EventPriorityType_Default, (void*)ompphp_event_onVehicleSpawn) && ok;
    ok = ompphp_api.Event.AddHandler("onVehicleStreamIn", EventPriorityType_Default, (void*)ompphp_event_onVehicleStreamIn) && ok;
    ok = ompphp_api.Event.AddHandler("onVehicleStreamOut", EventPriorityType_Default, (void*)ompphp_event_onVehicleStreamOut) && ok;
    return ok;
}

#endif
