<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Bullet hit types for OnPlayerWeaponShot. */
final class BulletHitType
{
    public const UNKNOWN = -1;
    public const NONE = 0;
    public const PLAYER = 1;
    public const VEHICLE = 2;
    public const OBJECT = 3;
    public const PLAYER_OBJECT = 4;
}
