<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Camera move types. */
final class CameraMoveType
{
    public const MOVE_UNKNOWN = -1;
    public const MOVE = 1;
    public const CUT = 2;
}
