<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Camera mode identifiers. */
final class CameraMode
{
    public const DISCONNECTED = -1;
    public const NONE = 0;
    public const BEHIND_CAR = 3;
    public const FOLLOW_PED = 4;
    public const SNIPER = 7;
    public const ROCKET_LAUNCHER = 8;
    public const FIXED = 15;
    public const FIRST_PERSON = 16;
    public const CAM_ON_A_STRING = 18;
    public const BEHIND_BOAT = 22;
    public const CAMERA = 46;
    public const ROCKET_LAUNCHER_HS = 51;
    public const AIM_WEAPON = 53;
    public const AIM_WEAPON_FROM_CAR = 55;
    public const DW_HELI_CHASE = 56;
}
