<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Vehicle mod slot identifiers. */
final class CarModType
{
    public const NONE = -1;
    public const SPOILER = 0;
    public const HOOD = 1;
    public const ROOF = 2;
    public const SIDESKIRT = 3;
    public const LAMPS = 4;
    public const NITRO = 5;
    public const EXHAUST = 6;
    public const WHEELS = 7;
    public const STEREO = 8;
    public const HYDRAULICS = 9;
    public const FRONT_BUMPER = 10;
    public const REAR_BUMPER = 11;
    public const VENT_RIGHT = 12;
    public const VENT_LEFT = 13;
    public const FRONT_BULLBAR = 14;
    public const REAR_BULLBAR = 15;
}
