<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Checkpoint and race checkpoint marker types. */
final class CheckpointType
{
    public const UNKNOWN = -1;
    public const GROUND_NORMAL = 0;
    public const GROUND_FINISH = 1;
    public const GROUND_EMPTY = 2;
    public const AIR_NORMAL = 3;
    public const AIR_FINISH = 4;
    public const AIR_ROTATING = 5;
    public const AIR_STROBING = 6;
    public const AIR_SWINGING = 7;
    public const AIR_BOBBING = 8;
}
