<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Sources for click callbacks. */
final class ClickSource
{
    public const UNKNOWN = -1;
    public const SCOREBOARD = 0;
}
