<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Network connection status values. */
final class ConnectionStatus
{
    public const UNKNOWN = -1;
    public const NO_ACTION = 0;
    public const DISCONNECT_ASAP = 1;
    public const DISCONNECT_ASAP_SILENTLY = 2;
    public const DISCONNECT_ON_NO_ACK = 3;
    public const REQUESTED_CONNECTION = 4;
    public const HANDLING_CONNECTION_REQUEST = 5;
    public const UNVERIFIED_SENDER = 6;
    public const SET_ENCRYPTION_ON_MULTIPLE16_BYTE_PACKET = 7;
    public const CONNECTED = 8;
}
