<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Dialog style identifiers. */
final class DialogStyle
{
    public const UNKNOWN = -1;
    public const MSG_BOX = 0;
    public const INPUT = 1;
    public const LIST = 2;
    public const PASSWORD = 3;
    public const TABLIST = 4;
    public const TABLIST_HEADERS = 5;
}
