<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Reasons a player disconnected. */
final class DisconnectReason
{
    public const TIMEOUT = 0;
    public const QUIT = 1;
    public const KICKED = 2;
}
