<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Download request types. */
final class DownloadRequest
{
    public const UNKNOWN = -1;
    public const EMPTY = 0;
    public const MODEL_FILE = 1;
    public const TEXTURE_FILE = 2;
}
