<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Object edit response identifiers. */
final class EditResponse
{
    public const UNKNOWN = -1;
    public const CANCEL = 0;
    public const FINAL = 1;
    public const UPDATE = 2;
}
