<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Hand-to-hand fight styles. */
final class FightStyle
{
    public const UNKNOWN = -1;
    public const NORMAL = 4;
    public const BOXING = 5;
    public const KUNG_FU = 6;
    public const KNEEHEAD = 7;
    public const GRABKICK = 15;
    public const ELBOW = 16;
}
