<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Forced sync targets for animations. */
final class ForceSync
{
    public const UNKNOWN = -1;
    public const NONE = 0;
    public const ALL = 1;
    public const OTHER = 2;
}
