<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** HTTP error response codes. */
final class HttpError
{
    public const UNKNOWN = -1;
    public const BAD_HOST = 1;
    public const NO_SOCKET = 2;
    public const CANT_CONNECT = 3;
    public const CANT_WRITE = 4;
    public const CONTENT_TOO_BIG = 5;
    public const MALFORMED_RESPONSE = 6;
}
