<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** HTTP request methods. */
final class HttpMethod
{
    public const METHOD_UNKNOWN = -1;
    public const GET = 1;
    public const POST = 2;
    public const HEAD = 3;
}
