<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Bitmask values for player key states. */
final class Keys
{
    public const NONE = 0;
    public const ACTION = 1;
    public const CROUCH = 2;
    public const FIRE = 4;
    public const SPRINT = 8;
    public const SECONDARY_ATTACK = 16;
    public const JUMP = 32;
    public const LOOK_RIGHT = 64;
    public const HANDBRAKE = 128;
    public const AIM = 128;
    public const LOOK_LEFT = 256;
    public const SUBMISSION = 512;
    public const LOOK_BEHIND = 512;
    public const WALK = 1024;
    public const ANALOG_UP = 2048;
    public const ANALOG_DOWN = 4096;
    public const ANALOG_LEFT = 8192;
    public const ANALOG_RIGHT = 16384;
    public const YES = 65536;
    public const NO = 131072;
    public const CTRL_BACK = 262144;
}
