<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Aircraft landing gear states. */
final class LandingGearState
{
    public const DOWN = 0;
    public const UP = 1;
}
