<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Map icon display styles. */
final class MapIconStyle
{
    public const STYLE_UNKNOWN = -1;
    public const LOCAL = 0;
    public const GLOBAL = 1;
    public const LOCAL_CHECKPOINT = 2;
    public const GLOBAL_CHECKPOINT = 3;
}
