<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** NPC entity check flags. */
final class NPCEntityCheck
{
    public const NONE = 0;
    public const PLAYER = 1;
    public const NPC = 2;
    public const ACTOR = 4;
    public const VEHICLE = 8;
    public const OBJECT = 16;
    public const P_OBJECT_ORIG = 32;
    public const P_OBJECT_TARG = 64;
    public const MAP = 128;
    public const ALL = 255;
}
