<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** NPC movement types. */
final class NPCMoveType
{
    public const UNKNOWN = -1;
    public const NONE = 0;
    public const WALK = 1;
    public const JOG = 2;
    public const SPRINT = 3;
    public const DRIVE = 4;
    public const AUTO = 5;
}
