<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Object material texture sizes. */
final class ObjectMaterialSize
{
    public const SIZE_UNKNOWN = -1;
    public const SIZE32X32 = 10;
    public const SIZE64X32 = 20;
    public const SIZE64X64 = 30;
    public const SIZE128X32 = 40;
    public const SIZE128X64 = 50;
    public const SIZE128X128 = 60;
    public const SIZE256X32 = 70;
    public const SIZE256X64 = 80;
    public const SIZE256X128 = 90;
    public const SIZE256X256 = 100;
    public const SIZE512X64 = 110;
    public const SIZE512X128 = 120;
    public const SIZE512X256 = 130;
    public const SIZE512X512 = 140;
}
