<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Object material text alignment identifiers. */
final class ObjectMaterialTextAlign
{
    public const UNKNOWN = -1;
    public const LEFT = 0;
    public const CENTRE = 1;
    public const CENTER = 1;
    public const RIGHT = 2;
}
