<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Player state identifiers. */
final class PlayerState
{
    public const UNKNOWN = -1;
    public const NONE = 0;
    public const ON_FOOT = 1;
    public const DRIVER = 2;
    public const PASSENGER = 3;
    public const WASTED = 7;
    public const SPAWNED = 8;
    public const SPECTATING = 9;
}
