<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Player recording types for NPC playback. */
final class PlayerRecordingType
{
    public const UNKNOWN = -1;
    public const NONE = 0;
    public const DRIVER = 1;
    public const ON_FOOT = 2;
}
