<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Player marker display modes. */
final class PlayerMarkersMode
{
    public const UNKNOWN = -1;
    public const OFF = 0;
    public const GLOBAL = 1;
    public const STREAMED = 2;
}
