<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Object selection types. */
final class SelectObjectType
{
    public const UNKNOWN = -1;
    public const GLOBAL_OBJECT = 1;
    public const PLAYER_OBJECT = 2;
}
