<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Spectate mode identifiers. */
final class SpectateMode
{
    public const UNKNOWN = -1;
    public const NORMAL = 1;
    public const FIXED = 2;
    public const SIDE = 3;
}
