<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Special action identifiers. */
final class SpecialAction
{
    public const UNKNOWN = -1;
    public const NONE = 0;
    public const DUCK = 1;
    public const USE_JETPACK = 2;
    public const ENTER_VEHICLE = 3;
    public const EXIT_VEHICLE = 4;
    public const DANCE1 = 5;
    public const DANCE2 = 6;
    public const DANCE3 = 7;
    public const DANCE4 = 8;
    public const HANDS_UP = 10;
    public const USE_CELLPHONE = 11;
    public const SITTING = 12;
    public const STOP_USE_CELLPHONE = 13;
    public const DRINK_BEER = 20;
    public const SMOKE_CIGGY = 21;
    public const DRINK_WINE = 22;
    public const DRINK_SPRUNK = 23;
    public const CUFFED = 24;
    public const CARRY = 25;
    public const PISSING = 68;
}
