<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Text draw font identifiers. */
final class TextDrawFont
{
    public const FONT_UNKNOWN = -1;
    public const FONT0 = 0;
    public const FONT1 = 1;
    public const FONT2 = 2;
    public const FONT3 = 3;
    public const FONT_SPRITE_DRAW = 4;
    public const FONT_MODEL_PREVIEW = 5;
    public const FONT_BANK = 0;
    public const FONT_STANDARD = 1;
    public const FONT_SPACEAGE = 2;
    public const FONT_HEADING = 3;
    public const FONT_BECKETT_REGULAR = 0;
    public const FONT_AHARONI_BOLD = 1;
    public const FONT_BANK_GOTHIC = 2;
    public const FONT_PRICEDOWN = 3;
    public const FONT_SPRITE = 4;
    public const FONT_PREVIEW = 5;
}
