<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Text draw alignment identifiers. */
final class TextDrawAlign
{
    public const UNKNOWN = -1;
    public const LEFT = 1;
    public const CENTRE = 2;
    public const CENTER = 2;
    public const RIGHT = 3;
}
