<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Server/player variable types. */
final class VarType
{
    public const UNKNOWN = -1;
    public const NONE = 0;
    public const INT = 1;
    public const STRING = 2;
    public const FLOAT = 3;
}
