<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Vehicle light damage status flags. */
final class VehicleLightStatus
{
    public const NONE = 0;
    public const FRONT_LEFT_BROKEN = 1;
    public const FRONT_RIGHT_BROKEN = 4;
    public const REAR_BROKEN = 64;
}
