<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Vehicle panel damage status values. */
final class VehiclePanelStatus
{
    public const UNKNOWN = -1;
    public const NONE = 0;
}
