<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Vehicle model info identifiers. */
final class VehicleModelInfo
{
    public const UNKNOWN = -1;
    public const SIZE = 1;
    public const FRONT_SEAT = 2;
    public const REAR_SEAT = 3;
    public const PETROL_CAP = 4;
    public const WHEELS_FRONT = 5;
    public const WHEELS_REAR = 6;
    public const WHEELS_MID = 7;
    public const FRONT_BUMPER = 8;
    public const REAR_BUMPER = 9;
}
