<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Vehicle parameter state values. */
final class VehicleParam
{
    public const UNSET = -1;
    public const OFF = 0;
    public const ON = 1;
}
