<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Vehicle tyre damage status flags. */
final class VehicleTyreStatus
{
    public const NONE = 0;
    public const FRONT_LEFT_POPPED = 8;
    public const FRONT_RIGHT_POPPED = 2;
    public const REAR_LEFT_POPPED = 4;
    public const REAR_RIGHT_POPPED = 1;
}
