<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Vehicle door damage status flags. */
final class VehicleDoorStatus
{
    public const NONE = 0;
    public const BONNET_OPEN = 1;
    public const BONNET_DAMAGED = 2;
    public const BONNET_MISSING = 4;
    public const BOOT_OPEN = 256;
    public const BOOT_DAMAGED = 512;
    public const BOOT_MISSING = 1024;
    public const FRONT_LEFT_OPEN = 65536;
    public const FRONT_LEFT_DAMAGED = 131072;
    public const FRONT_LEFT_MISSING = 262144;
    public const FRONT_RIGHT_OPEN = 16777216;
    public const FRONT_RIGHT_DAMAGED = 33554432;
    public const FRONT_RIGHT_MISSING = 67108864;
}
