<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Weapon identifiers. */
final class WeaponID
{
    public const FIST = 0;
    public const BRASS_KNUCKLES = 1;
    public const GOLF_CLUB = 2;
    public const NITESTICK = 3;
    public const KNIFE = 4;
    public const BAT = 5;
    public const SHOVEL = 6;
    public const POOL_STICK = 7;
    public const KATANA = 8;
    public const CHAINSAW = 9;
    public const DILDO = 10;
    public const DILDO2 = 11;
    public const VIBRATOR = 12;
    public const VIBRATOR2 = 13;
    public const FLOWERS = 14;
    public const CANE = 15;
    public const GRENADE = 16;
    public const TEARGAS = 17;
    public const MOLOTOV = 18;
    public const COLT45 = 22;
    public const SILENCED = 23;
    public const DEAGLE = 24;
    public const SHOTGUN = 25;
    public const SAWEDOFF = 26;
    public const COMBAT_SHOTGUN = 27;
    public const UZI = 28;
    public const MP5 = 29;
    public const AK47 = 30;
    public const M4 = 31;
    public const TEC9 = 32;
    public const RIFLE = 33;
    public const SNIPER = 34;
    public const RPG = 35;
    public const HEATSEEKER = 36;
    public const FLAMETHROWER = 37;
    public const MINIGUN = 38;
    public const SATCHEL = 39;
    public const BOMB = 40;
    public const SPRAYCAN = 41;
    public const FIRE_EXTINGUISHER = 42;
    public const CAMERA = 43;
    public const NIGHT_VISION_GOGGLES = 44;
    public const THERMAL_GOGGLES = 45;
    public const PARACHUTE = 46;
    public const VEHICLE = 49;
    public const DROWN = 53;
    public const COLLISION = 54;
}
