<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Weapon state identifiers. */
final class WeaponState
{
    public const UNKNOWN = -1;
    public const NO_BULLETS = 0;
    public const LAST_BULLET = 1;
    public const MORE_BULLETS = 2;
    public const RELOADING = 3;
}
