<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Weapon slot identifiers. */
final class WeaponSlot
{
    public const UNKNOWN = -1;
    public const UNARMED = 0;
    public const MELEE = 1;
    public const PISTOL = 2;
    public const SHOTGUN = 3;
    public const MACHINE_GUN = 4;
    public const ASSAULT_RIFLE = 5;
    public const LONG_RIFLE = 6;
    public const ARTILLERY = 7;
    public const EXPLOSIVES = 8;
    public const EQUIPMENT = 9;
    public const GIFT = 10;
    public const GADGET = 11;
    public const DETONATOR = 12;
}
