<?php

declare(strict_types=1);

namespace Omp\Constant;

// Code generated by tools/codegen. DO NOT EDIT.

/** Weapon skill identifiers. */
final class WeaponSkill
{
    public const UNKNOWN = -1;
    public const PISTOL = 0;
    public const PISTOL_SILENCED = 1;
    public const DESERT_EAGLE = 2;
    public const SHOTGUN = 3;
    public const SAWNOFF_SHOTGUN = 4;
    public const SPAS12_SHOTGUN = 5;
    public const MICRO_UZI = 6;
    public const MP5 = 7;
    public const AK47 = 8;
    public const M4 = 9;
    public const SNIPER_RIFLE = 10;
}
