package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type constantsManifest struct {
	Version  int               `json:"version"`
	Comments map[string]string `json:"comments"`
	Groups   []constantGroup   `json:"groups"`
}

type constantGroup struct {
	Name    string         `json:"name"`
	Type    string         `json:"type"`
	Comment string         `json:"comment"`
	Items   []constantItem `json:"items"`
}

type constantItem struct {
	Name    string `json:"name"`
	Value   int    `json:"value"`
	Comment string `json:"comment"`
}

func loadConstants(path string) (constantsManifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return constantsManifest{}, fmt.Errorf("read constants manifest: %w", err)
	}
	var manifest constantsManifest
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&manifest); err != nil {
		return constantsManifest{}, fmt.Errorf("parse constants manifest: %w", err)
	}
	if manifest.Version != 2 {
		return constantsManifest{}, fmt.Errorf("unsupported constants manifest version %d", manifest.Version)
	}
	seenGroups := make(map[string]bool, len(manifest.Groups))
	for _, group := range manifest.Groups {
		if group.Name == "" {
			return constantsManifest{}, fmt.Errorf("constants group has no name")
		}
		if seenGroups[group.Name] {
			return constantsManifest{}, fmt.Errorf("duplicate constants group %q", group.Name)
		}
		seenGroups[group.Name] = true
		if group.Type != "enum" && group.Type != "bitflags" {
			return constantsManifest{}, fmt.Errorf("constants group %q has unsupported type %q", group.Name, group.Type)
		}
		seenItems := make(map[string]bool, len(group.Items))
		for _, item := range group.Items {
			if item.Name == "" {
				return constantsManifest{}, fmt.Errorf("constants group %q has an unnamed item", group.Name)
			}
			if seenItems[item.Name] {
				return constantsManifest{}, fmt.Errorf("constants group %q contains duplicate item %q", group.Name, item.Name)
			}
			seenItems[item.Name] = true
		}
	}
	return manifest, nil
}

func generateConstants(outDir string, manifest constantsManifest) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create constants output directory: %w", err)
	}
	for _, group := range manifest.Groups {
		var out bytes.Buffer
		out.WriteString("<?php\n\ndeclare(strict_types=1);\n\nnamespace Omp\\Constant;\n\n// Code generated by tools/codegen. DO NOT EDIT.\n\n")
		if group.Comment != "" {
			fmt.Fprintf(&out, "/** %s */\n", strings.TrimSpace(group.Comment))
		}
		fmt.Fprintf(&out, "final class %s\n{\n", group.Name)
		prefix := commonConstantPrefix(group.Items)
		for _, item := range group.Items {
			name := strings.TrimPrefix(strings.ToUpper(snake(item.Name)), prefix)
			name = strings.TrimPrefix(name, "_")
			if name == "" {
				name = strings.ToUpper(snake(item.Name))
			}
			if item.Comment != "" {
				fmt.Fprintf(&out, "    /** %s */\n", strings.TrimSpace(item.Comment))
			}
			fmt.Fprintf(&out, "    public const %s = %d;\n", name, item.Value)
		}
		out.WriteString("}\n")
		path := filepath.Join(outDir, group.Name+".php")
		if err := os.WriteFile(path, out.Bytes(), 0o644); err != nil {
			return fmt.Errorf("write generated constants %s: %w", group.Name, err)
		}
	}
	return nil
}

func commonConstantPrefix(items []constantItem) string {
	if len(items) == 0 {
		return ""
	}
	prefix := strings.Split(strings.ToUpper(snake(items[0].Name)), "_")
	for _, item := range items[1:] {
		words := strings.Split(strings.ToUpper(snake(item.Name)), "_")
		length := len(prefix)
		if len(words) < length {
			length = len(words)
		}
		i := 0
		for i < length && prefix[i] == words[i] {
			i++
		}
		prefix = prefix[:i]
	}
	return strings.Join(prefix, "_")
}
