package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/ompphp/ompphp/tools/codegen/model"
)

func generateEventBridge(headerPath, goPath string, m model.Model) (int, error) {
	var header bytes.Buffer
	header.WriteString(`// Code generated by tools/codegen. DO NOT EDIT.
#ifndef OMPPHP_EVENTS_GENERATED_H
#define OMPPHP_EVENTS_GENERATED_H

struct OMPPHPEventArg { int kind; int64_t integer; double number; const char* text; unsigned int length; };
extern struct OMPAPI_t ompphp_api;
extern int ompphp_player_id(void* player);
extern bool OMPPHPDispatchGeneratedEvent(char* name, struct OMPPHPEventArg* args, int count, bool default_result);

`)
	count := 0
	for _, e := range m.Events {
		if !directEvent(e) {
			continue
		}
		writeCEvent(&header, e)
		count++
	}
	header.WriteString("static bool ompphp_register_generated_events(void) {\n    bool ok = true;\n")
	for _, e := range m.Events {
		if !directEvent(e) {
			continue
		}
		fmt.Fprintf(&header, "    ok = ompphp_api.Event.AddHandler(\"%s\", EventPriorityType_Default, (void*)ompphp_event_%s) && ok;\n", e.Name, e.Name)
	}
	header.WriteString("    return ok;\n}\n\n#endif\n")
	body := []byte(`// Code generated by tools/codegen. DO NOT EDIT.
package main

/*
#cgo CFLAGS: -I${SRCDIR}/../../third_party/omp-capi/lib/open.mp-capi/include
#include "ompcapi.h"
#include "events_generated.h"
*/
import "C"

import "unsafe"

//export OMPPHPDispatchGeneratedEvent
func OMPPHPDispatchGeneratedEvent(name *C.char, raw *C.struct_OMPPHPEventArg, count C.int, defaultResult C.bool) C.bool {
    component.Lock()
    active := component.runtime
    component.Unlock()
    fallback := bool(defaultResult)
    if active == nil { return C.bool(fallback) }
    cargs := unsafe.Slice(raw, int(count))
    arguments := make([]any, 0, len(cargs))
    for _, argument := range cargs {
        switch int(argument.kind) {
        case 1: arguments = append(arguments, int64(argument.integer))
        case 2: arguments = append(arguments, float64(argument.number))
        case 3: arguments = append(arguments, argument.integer != 0)
        case 4: arguments = append(arguments, C.GoStringN(argument.text, C.int(argument.length)))
        }
    }
    return C.bool(active.DispatchDefault(C.GoString(name), fallback, arguments...))
}
`)
	formatted, err := format.Source(body)
	if err != nil {
		return 0, fmt.Errorf("format generated event Go: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(headerPath), 0o755); err != nil {
		return 0, err
	}
	if err := os.WriteFile(headerPath, header.Bytes(), 0o644); err != nil {
		return 0, err
	}
	if err := os.WriteFile(goPath, formatted, 0o644); err != nil {
		return 0, err
	}
	return count, nil
}

func directEvent(e model.Event) bool {
	for i, p := range e.Parameters {
		t := strings.TrimSpace(p.Type)
		if t == "void*" {
			if eventEntity(e, p, i) == "" {
				return false
			}
			continue
		}
		if t != "int" && t != "float" && t != "bool" && t != "CAPIStringView" {
			return false
		}
	}
	return true
}

func eventEntity(e model.Event, p model.Parameter, index int) string {
	switch p.Name {
	case "player", "forPlayer", "killer", "damager", "damaged", "from", "to":
		return "Player"
	case "actor":
		return "Actor"
	case "vehicle", "trailer":
		return "Vehicle"
	case "npc", "npcTarget":
		return "NPC"
	case "zone":
		return "GangZone"
	case "pickup":
		return "Pickup"
	case "clicked":
		if strings.Contains(e.Name, "ClickPlayer") {
			return "Player"
		}
	case "target":
		switch {
		case strings.Contains(e.Name, "Vehicle"):
			return "Vehicle"
		case strings.Contains(e.Name, "NPC"):
			return "NPC"
		case strings.Contains(e.Name, "Object") && !strings.Contains(e.Name, "PlayerObject"):
			return "Object"
		case strings.Contains(e.Name, "Player"):
			return "Player"
		}
	case "object":
		if strings.Contains(e.Name, "PlayerObject") && eventHasParameter(e, "player") {
			return "PlayerObject"
		}
		if !strings.Contains(e.Name, "PlayerObject") {
			return "Object"
		}
	case "playerObject":
		if eventHasParameter(e, "player") || e.Name == "onNPCShotPlayerObject" {
			return "PlayerObject"
		}
	case "textdraw":
		if strings.Contains(e.Name, "PlayerTextDraw") {
			return "PlayerTextDraw"
		}
		return "TextDraw"
	}
	return ""
}

func eventHasParameter(e model.Event, name string) bool {
	for _, parameter := range e.Parameters {
		if parameter.Name == name {
			return true
		}
	}
	return false
}

func writeCEvent(out *bytes.Buffer, e model.Event) {
	fallback := "true"
	if e.ReturnType == "false" {
		fallback = "false"
	}
	phpName := strings.TrimPrefix(e.Name, "on")
	if phpName == e.Name {
		phpName = strings.TrimPrefix(e.Name, "On")
	}
	fmt.Fprintf(out, "static bool ompphp_event_%s(struct EventArgs_%s* event) {\n", e.Name, e.Name)
	fmt.Fprintf(out, "    if (!event || event->size < 1 || !event->list) return %s;\n", fallback)
	if len(e.Parameters) > 0 {
		fmt.Fprintf(out, "    struct OMPPHPEventArg values[%d] = {0};\n", len(e.Parameters))
	}
	for i, p := range e.Parameters {
		t := strings.TrimSpace(p.Type)
		field := "event->list[0]." + p.Name
		switch t {
		case "void*":
			entity := eventEntity(e, p, i)
			if entity == "PlayerObject" && e.Name == "onNPCShotPlayerObject" {
				fmt.Fprintf(out, "    void* npcPlayer%d = event->list[0].npc && *event->list[0].npc && ompphp_api.NPC.GetPlayer ? ompphp_api.NPC.GetPlayer(*event->list[0].npc) : NULL;\n", i)
				fmt.Fprintf(out, "    values[%d].kind = 1; values[%d].integer = %s && *%s && npcPlayer%d && ompphp_api.PlayerObject.GetID ? ompphp_api.PlayerObject.GetID(npcPlayer%d, *%s) : -1;\n", i, i, field, field, i, i, field)
			} else if entity == "PlayerObject" || entity == "PlayerTextDraw" {
				fmt.Fprintf(out, "    values[%d].kind = 1; values[%d].integer = %s && *%s && event->list[0].player && *event->list[0].player && ompphp_api.%s.GetID ? ompphp_api.%s.GetID(*event->list[0].player, *%s) : -1;\n", i, i, field, field, entity, entity, field)
			} else {
				fmt.Fprintf(out, "    values[%d].kind = 1; values[%d].integer = %s && *%s && ompphp_api.%s.GetID ? ompphp_api.%s.GetID(*%s) : -1;\n", i, i, field, field, entity, entity, field)
			}
		case "int":
			fmt.Fprintf(out, "    values[%d].kind = 1; values[%d].integer = %s ? *%s : 0;\n", i, i, field, field)
		case "float":
			fmt.Fprintf(out, "    values[%d].kind = 2; values[%d].number = %s ? *%s : 0;\n", i, i, field, field)
		case "bool":
			fmt.Fprintf(out, "    values[%d].kind = 3; values[%d].integer = %s && *%s;\n", i, i, field, field)
		case "CAPIStringView":
			fmt.Fprintf(out, "    values[%d].kind = 4; if (%s) { values[%d].text = %s->data; values[%d].length = %s->len; }\n", i, field, i, field, i, field)
		}
	}
	pointer := "NULL"
	if len(e.Parameters) > 0 {
		pointer = "values"
	}
	fmt.Fprintf(out, "    return OMPPHPDispatchGeneratedEvent(\"%s\", %s, %d, %s);\n}\n\n", phpName, pointer, len(e.Parameters), fallback)
}
