package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/ompphp/ompphp/tools/codegen/model"
)

func generateNative(headerPath, goPath string, m model.Model) (int, error) {
	fromID := map[string]bool{}
	for _, f := range m.Functions {
		if f.Name == f.Group+"_FromID" && ((len(f.Parameters) == 1 && isIntegerC(strings.TrimSpace(f.Parameters[0].Type))) || isCompositeEntity(f.Group)) {
			fromID[f.Group] = true
		}
	}
	var header, body bytes.Buffer
	header.WriteString("// Code generated by tools/codegen. DO NOT EDIT.\n#ifndef OMPPHP_NATIVE_GENERATED_H\n#define OMPPHP_NATIVE_GENERATED_H\n\nextern struct OMPAPI_t ompphp_api;\n\n")
	body.WriteString(`// Code generated by tools/codegen. DO NOT EDIT.
package main

/*
#cgo CFLAGS: -I${SRCDIR}/../../third_party/openmp-capi/include
#include <stdlib.h>
#include "ompcapi.h"
#include "native_generated.h"
*/
import "C"

import (
    "errors"
    "fmt"
    "unsafe"
)

func callGenerated(name string, arguments []any) (any, bool, error) {
    switch name {
`)
	count := 0
	for _, f := range m.Functions {
		entity, ok := directNative(f, fromID)
		if !ok {
			continue
		}
		writeCAdapter(&header, f, entity, fromID)
		writeGoAdapter(&body, f)
		count++
	}
	header.WriteString("\n#endif\n")
	body.WriteString("    }\n    return nil, false, nil\n}\n\n")
	body.WriteString(`func generatedInt(value any, position int) (C.int64_t, error) {
    integer, ok := asInt(value)
    if !ok { return 0, fmt.Errorf("argument %d must be an integer", position) }
    return C.int64_t(integer), nil
}
func generatedFloat(value any, position int) (C.double, error) {
    number, ok := value.(float64)
    if !ok { return 0, fmt.Errorf("argument %d must be floating-point", position) }
    return C.double(number), nil
}
func generatedBool(value any, position int) (C.bool, error) {
    boolean, ok := value.(bool)
    if !ok { return false, fmt.Errorf("argument %d must be boolean", position) }
    return C.bool(boolean), nil
}
func generatedString(value any, position int) (*C.char, error) {
    text, ok := value.(string)
    if !ok { return nil, fmt.Errorf("argument %d must be a string", position) }
    return C.CString(text), nil
}
var _ = errors.New
var _ unsafe.Pointer
`)
	formatted, err := format.Source(body.Bytes())
	if err != nil {
		return 0, fmt.Errorf("format generated native Go: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(headerPath), 0o755); err != nil {
		return 0, err
	}
	if err := os.WriteFile(headerPath, header.Bytes(), 0o644); err != nil {
		return 0, err
	}
	if err := os.WriteFile(goPath, formatted, 0o644); err != nil {
		return 0, err
	}
	return count, nil
}

func directNative(f model.Function, fromID map[string]bool) (bool, bool) {
	if f.Group == "Component" || f.Group == "Event" {
		return false, false
	}
	returnEntity := entityReturnGroup(f)
	if !scalarReturn(f.ReturnType) && returnEntity == "" {
		return false, false
	}
	voids := 0
	for i, p := range f.Parameters {
		if p.Output {
			if !scalarOutput(p.Type) {
				return false, false
			}
			continue
		}
		if !scalarInput(p.Type) {
			return false, false
		}
		if strings.TrimSpace(p.Type) == "void*" {
			group := nativeParamEntity(f, p, i)
			if group == "" || !fromID[group] {
				return false, false
			}
			voids++
		}
	}
	return voids > 0, true
}

func entityReturnGroup(f model.Function) string {
	if strings.TrimSpace(f.ReturnType) != "void*" {
		return ""
	}
	method := strings.TrimPrefix(f.Name, f.Group+"_")
	if strings.HasPrefix(method, "Create") || strings.HasPrefix(method, "Add") || method == "FromID" {
		return f.Group
	}
	for _, group := range []string{"PlayerObject", "PlayerTextDraw", "PlayerTextLabel", "Vehicle", "Player", "Actor", "Object", "Menu", "Pickup", "GangZone", "TextDraw", "TextLabel", "NPC"} {
		if strings.Contains(method, group) {
			return group
		}
	}
	if strings.HasPrefix(method, "Get") && (f.Group == "Vehicle" || f.Group == "Actor" || f.Group == "Object" || f.Group == "Menu" || f.Group == "Pickup" || f.Group == "GangZone" || f.Group == "TextDraw" || f.Group == "TextLabel" || f.Group == "NPC") {
		return f.Group
	}
	return ""
}

func nativeParamEntity(f model.Function, p model.Parameter, index int) string {
	name := strings.ToLower(p.Name)
	switch name {
	case "player", "forplayer", "other", "source", "killer", "damager", "atplayer", "playerattachedto", "sender", "suspect", "killee", "attachedplayer":
		return "Player"
	case "vehicle", "trailer", "attachedvehicle":
		return "Vehicle"
	case "actor":
		return "Actor"
	case "npc":
		return "NPC"
	case "object":
		if strings.Contains(f.Name, "PlayerObject") {
			return "PlayerObject"
		}
		return "Object"
	case "attachedto", "objattachedto":
		return "Object"
	case "gangzone":
		return "GangZone"
	case "pickup":
		return "Pickup"
	case "targetvehicle":
		return "Vehicle"
	case "textdraw":
		if f.Group == "PlayerTextDraw" || strings.Contains(f.Name, "PlayerTextDraw") {
			return "PlayerTextDraw"
		}
		return "TextDraw"
	case "textlabel":
		if f.Group == "PlayerTextLabel" || strings.Contains(f.Name, "PlayerTextLabel") {
			return "PlayerTextLabel"
		}
		return "TextLabel"
	case "target":
		switch {
		case strings.Contains(f.Name, "Vehicle"):
			return "Vehicle"
		case strings.Contains(f.Name, "Actor"):
			return "Actor"
		case strings.Contains(f.Name, "NPC"):
			return "NPC"
		case strings.Contains(f.Name, "Object") && !strings.Contains(f.Name, "PlayerObject"):
			return "Object"
		default:
			return "Player"
		}
	}
	if index == 0 {
		return f.Group
	}
	return ""
}

func optionalEntityParameter(name string) bool {
	name = strings.ToLower(name)
	return name == "attachedplayer" || name == "attachedvehicle" || name == "attachedto" || name == "objattachedto"
}

func isCompositeEntity(group string) bool {
	return group == "PlayerObject" || group == "PlayerTextDraw" || group == "PlayerTextLabel"
}

func nativeUnsupportedReason(f model.Function, fromID map[string]bool) string {
	if f.Group == "Component" || f.Group == "Event" {
		return "component infrastructure"
	}
	returnEntity := entityReturnGroup(f)
	if !scalarReturn(f.ReturnType) && returnEntity == "" {
		return "non-scalar return"
	}
	for i, p := range f.Parameters {
		if p.Output {
			if !scalarOutput(p.Type) {
				return "string/complex output"
			}
			continue
		}
		if !scalarInput(p.Type) {
			return "complex input"
		}
		if strings.TrimSpace(p.Type) == "void*" {
			group := nativeParamEntity(f, p, i)
			if group == "" {
				return "unknown entity input"
			}
			if !fromID[group] {
				return "composite entity lookup"
			}
		}
	}
	return "supported"
}

func scalarOutput(t string) bool {
	t = strings.TrimSpace(t)
	if !strings.HasSuffix(t, "*") {
		return false
	}
	base := strings.TrimSpace(strings.TrimSuffix(t, "*"))
	return base == "CAPIStringView" || base == "CAPIStringBuffer" || base == "bool" || base == "float" || base == "double" || isIntegerC(base)
}

func scalarReturn(t string) bool {
	t = strings.TrimSpace(t)
	return t == "void" || t == "bool" || t == "float" || t == "double" || isIntegerC(t)
}
func scalarInput(t string) bool {
	t = strings.TrimSpace(t)
	return t == "void*" || t == "const char*" || t == "bool" || t == "float" || t == "double" || isIntegerC(t)
}
func isIntegerC(t string) bool {
	return t == "int" || t == "unsigned int" || t == "long" || t == "unsigned long" || strings.HasPrefix(t, "uint") || strings.HasPrefix(t, "int")
}

func writeCAdapter(out *bytes.Buffer, f model.Function, entity bool, fromID map[string]bool) {
	method := strings.TrimPrefix(f.Name, f.Group+"_")
	returnEntity := entityReturnGroup(f)
	adapterReturn := f.ReturnType
	if returnEntity != "" {
		adapterReturn = "int64_t"
	}
	fmt.Fprintf(out, "static %s ompphp_gen_%s(", adapterReturn, f.Name)
	for i, p := range f.Parameters {
		if i > 0 {
			out.WriteString(", ")
		}
		if p.Output {
			fmt.Fprintf(out, "%s p%d", cTypeName(p.Type), i)
		} else if strings.TrimSpace(p.Type) == "void*" {
			fmt.Fprintf(out, "int64_t p%d", i)
		} else if isIntegerC(strings.TrimSpace(p.Type)) {
			fmt.Fprintf(out, "int64_t p%d", i)
		} else if p.Type == "float" || p.Type == "double" {
			fmt.Fprintf(out, "double p%d", i)
		} else {
			fmt.Fprintf(out, "%s p%d", p.Type, i)
		}
	}
	out.WriteString(") {\n")
	if entity {
		for i, p := range f.Parameters {
			if strings.TrimSpace(p.Type) != "void*" {
				continue
			}
			group := nativeParamEntity(f, p, i)
			if isCompositeEntity(group) {
				fmt.Fprintf(out, "    void* entity%d = entity0 && ompphp_api.%s.FromID ? ompphp_api.%s.FromID(entity0, (int)p%d) : NULL;\n", i, group, group, i)
			} else {
				if optionalEntityParameter(p.Name) {
					fmt.Fprintf(out, "    void* entity%d = p%d < 0 ? NULL : (ompphp_api.%s.FromID ? ompphp_api.%s.FromID((int)p%d) : NULL);\n", i, i, group, group, i)
				} else {
					fmt.Fprintf(out, "    void* entity%d = ompphp_api.%s.FromID ? ompphp_api.%s.FromID((int)p%d) : NULL;\n", i, group, group, i)
				}
			}
			if !optionalEntityParameter(p.Name) {
				fmt.Fprintf(out, "    if (!entity%d) %s\n", i, cDefaultReturn(f.ReturnType))
			}
		}
	}
	fmt.Fprintf(out, "    if (!ompphp_api.%s.%s) %s\n", f.Group, method, cDefaultReturn(adapterReturn))
	if returnEntity != "" {
		fmt.Fprintf(out, "    void* returned = ompphp_api.%s.%s(", f.Group, method)
		for i, p := range f.Parameters {
			if i > 0 {
				out.WriteString(", ")
			}
			if strings.TrimSpace(p.Type) == "void*" {
				fmt.Fprintf(out, "entity%d", i)
			} else if isIntegerC(strings.TrimSpace(p.Type)) {
				fmt.Fprintf(out, "(%s)p%d", p.Type, i)
			} else if p.Type == "float" || p.Type == "double" {
				fmt.Fprintf(out, "(%s)p%d", p.Type, i)
			} else {
				fmt.Fprintf(out, "p%d", i)
			}
		}
		out.WriteString(");\n    if (!returned) return -1;\n")
		if isCompositeEntity(returnEntity) {
			fmt.Fprintf(out, "    return entity0 && ompphp_api.%s.GetID ? ompphp_api.%s.GetID(entity0, returned) : -1;\n}\n\n", returnEntity, returnEntity)
		} else {
			fmt.Fprintf(out, "    return ompphp_api.%s.GetID ? ompphp_api.%s.GetID(returned) : -1;\n}\n\n", returnEntity, returnEntity)
		}
		return
	}
	if f.ReturnType != "void" {
		out.WriteString("    return ")
	} else {
		out.WriteString("    ")
	}
	fmt.Fprintf(out, "ompphp_api.%s.%s(", f.Group, method)
	for i, p := range f.Parameters {
		if i > 0 {
			out.WriteString(", ")
		}
		if p.Output {
			fmt.Fprintf(out, "p%d", i)
		} else if strings.TrimSpace(p.Type) == "void*" {
			fmt.Fprintf(out, "entity%d", i)
		} else if isIntegerC(strings.TrimSpace(p.Type)) {
			fmt.Fprintf(out, "(%s)p%d", p.Type, i)
		} else if p.Type == "float" || p.Type == "double" {
			fmt.Fprintf(out, "(%s)p%d", p.Type, i)
		} else {
			fmt.Fprintf(out, "p%d", i)
		}
	}
	out.WriteString(");\n}\n\n")
}

func cDefaultReturn(returnType string) string {
	if strings.TrimSpace(returnType) == "void" {
		return "return;"
	}
	return "return 0;"
}

func writeGoAdapter(out *bytes.Buffer, f model.Function) {
	fmt.Fprintf(out, "    case %q:\n", f.Name)
	if f.Name == "NPC_GetAll" {
		out.WriteString(`        if len(arguments) != 1 { return nil, true, fmt.Errorf("expected 1 argument, got %d", len(arguments)) }
        maximum, err := generatedInt(arguments[0], 1); if err != nil { return nil, true, err }
        if maximum < 0 || maximum > 10000 { return nil, true, errors.New("maximum NPC count must be between 0 and 10000") }
        if maximum == 0 { return []any{}, true, nil }
        data := C.calloc(C.size_t(maximum), C.size_t(C.sizeof_int)); if data == nil { return nil, true, errors.New("allocate NPC ID array") }; defer C.free(data)
        count := int(C.ompphp_gen_NPC_GetAll((*C.int)(data), maximum)); if count < 0 || count > int(maximum) { return nil, true, errors.New("NPC_GetAll returned an invalid count") }
        ids := unsafe.Slice((*C.int)(data), count); result := make([]any, len(ids)); for i, id := range ids { result[i] = int64(id) }
        return result, true, nil
`)
		return
	}
	inputCount := 0
	for _, p := range f.Parameters {
		if !p.Output {
			inputCount++
		}
	}
	fmt.Fprintf(out, "        if len(arguments) != %d { return nil, true, fmt.Errorf(\"expected %d arguments, got %%d\", len(arguments)) }\n", inputCount, inputCount)
	argumentIndex := 0
	for i, p := range f.Parameters {
		if p.Output {
			base := strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(p.Type), "*"))
			if base == "CAPIStringView" {
				fmt.Fprintf(out, "        var p%d C.struct_CAPIStringView\n", i)
			} else if base == "CAPIStringBuffer" {
				fmt.Fprintf(out, "        var p%d C.struct_CAPIStringBuffer\n        p%dData := C.malloc(C.size_t(16384)); if p%dData == nil { return nil, true, errors.New(\"allocate C string buffer\") }; defer C.free(p%dData)\n        p%d.capacity = C.uint(16384); p%d.data = (*C.char)(p%dData)\n", i, i, i, i, i, i, i)
			} else {
				fmt.Fprintf(out, "        var p%d C.%s\n", i, cgoType(base))
			}
			continue
		}
		kind := strings.TrimSpace(p.Type)
		switch {
		case kind == "void*" || isIntegerC(kind):
			fmt.Fprintf(out, "        p%d, err := generatedInt(arguments[%d], %d); if err != nil { return nil, true, err }\n", i, argumentIndex, argumentIndex+1)
		case kind == "float" || kind == "double":
			fmt.Fprintf(out, "        p%d, err := generatedFloat(arguments[%d], %d); if err != nil { return nil, true, err }\n", i, argumentIndex, argumentIndex+1)
		case kind == "bool":
			fmt.Fprintf(out, "        p%d, err := generatedBool(arguments[%d], %d); if err != nil { return nil, true, err }\n", i, argumentIndex, argumentIndex+1)
		case kind == "const char*":
			fmt.Fprintf(out, "        p%d, err := generatedString(arguments[%d], %d); if err != nil { return nil, true, err }; defer C.free(unsafe.Pointer(p%d))\n", i, argumentIndex, argumentIndex+1, i)
		}
		argumentIndex++
	}
	call := "C.ompphp_gen_" + f.Name + "("
	for i := range f.Parameters {
		if i > 0 {
			call += ", "
		}
		if f.Parameters[i].Output {
			call += fmt.Sprintf("&p%d", i)
		} else {
			call += fmt.Sprintf("p%d", i)
		}
	}
	call += ")"
	outputs := make([]int, 0)
	for i, p := range f.Parameters {
		if p.Output {
			outputs = append(outputs, i)
		}
	}
	if len(outputs) > 0 {
		if strings.TrimSpace(f.ReturnType) == "bool" {
			fmt.Fprintf(out, "        if !bool(%s) { return nil, true, errors.New(\"open.mp rejected %s\") }\n", call, f.Name)
		} else {
			fmt.Fprintf(out, "        %s\n", call)
		}
		if len(outputs) == 1 {
			fmt.Fprintf(out, "        return %s, true, nil\n", goOutputValue(f.Parameters[outputs[0]].Type, outputs[0]))
		} else {
			out.WriteString("        return []any{")
			for j, i := range outputs {
				if j > 0 {
					out.WriteString(", ")
				}
				out.WriteString(goOutputValue(f.Parameters[i].Type, i))
			}
			out.WriteString("}, true, nil\n")
		}
		return
	}
	switch strings.TrimSpace(f.ReturnType) {
	case "void":
		fmt.Fprintf(out, "        %s; return nil, true, nil\n", call)
	case "bool":
		fmt.Fprintf(out, "        return bool(%s), true, nil\n", call)
	case "float", "double":
		fmt.Fprintf(out, "        return float64(%s), true, nil\n", call)
	default:
		fmt.Fprintf(out, "        return int64(%s), true, nil\n", call)
	}
}

func cgoType(cType string) string {
	switch cType {
	case "bool":
		return "bool"
	case "float":
		return "float"
	case "double":
		return "double"
	case "int":
		return "int"
	case "unsigned int":
		return "uint"
	default:
		return strings.ReplaceAll(cType, " ", "_")
	}
}

func cTypeName(cType string) string {
	if cType == "CAPIStringView*" {
		return "struct CAPIStringView*"
	}
	if cType == "CAPIStringBuffer*" {
		return "struct CAPIStringBuffer*"
	}
	return cType
}

func goOutputValue(cType string, index int) string {
	base := strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(cType), "*"))
	switch base {
	case "CAPIStringView":
		return fmt.Sprintf("C.GoStringN(p%d.data, C.int(p%d.len))", index, index)
	case "CAPIStringBuffer":
		return fmt.Sprintf("C.GoStringN(p%d.data, C.int(p%d.len))", index, index)
	case "bool":
		return fmt.Sprintf("bool(p%d)", index)
	case "float", "double":
		return fmt.Sprintf("float64(p%d)", index)
	default:
		return fmt.Sprintf("int64(p%d)", index)
	}
}
