package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"

	"github.com/ompphp/ompphp/tools/codegen/model"
)

var acronymBoundary = regexp.MustCompile(`([A-Z]+)([A-Z][a-z])`)
var wordBoundary = regexp.MustCompile(`([a-z0-9])([A-Z])`)

func generatePHP(path string, m model.Model) error {
	var out bytes.Buffer
	out.WriteString("<?php\n\ndeclare(strict_types=1);\n\nnamespace Omp\\Internal;\n\n// Code generated by tools/codegen. DO NOT EDIT.\n\n")
	for _, function := range m.Functions {
		if !phpCallable(function) {
			continue
		}
		outputs := make([]model.Parameter, 0, len(function.Parameters))
		for _, parameter := range function.Parameters {
			if parameter.Output {
				outputs = append(outputs, parameter)
			}
		}
		returnType := "mixed"
		if len(outputs) > 1 {
			parts := make([]string, len(outputs))
			for i, output := range outputs {
				parts[i] = phpType(strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(output.Type), "*")))
			}
			fmt.Fprintf(&out, "/** @return array{%s} */\n", strings.Join(parts, ", "))
			returnType = "array"
		} else if function.Name == "NPC_GetAll" {
			out.WriteString("/** @return list<int> */\n")
			returnType = "array"
		} else if len(outputs) == 1 {
			returnType = phpType(strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(outputs[0].Type), "*")))
		} else {
			returnType = phpType(function.ReturnType)
		}
		fmt.Fprintf(&out, "function %s(", snake(function.Name))
		inputIndex := 0
		for _, p := range function.Parameters {
			if p.Output {
				continue
			}
			if inputIndex > 0 {
				out.WriteString(", ")
			}
			fmt.Fprintf(&out, "%s $%s", phpType(p.Type), safePHPName(p.Name))
			inputIndex++
		}
		fmt.Fprintf(&out, "): %s\n{\n", returnType)
		var call strings.Builder
		fmt.Fprintf(&call, "native_call('%s'", function.Name)
		for _, p := range function.Parameters {
			if p.Output {
				continue
			}
			fmt.Fprintf(&call, ", $%s", safePHPName(p.Name))
		}
		call.WriteString(")")
		if len(outputs) > 1 {
			fmt.Fprintf(&out, "    $result = %s;\n", call.String())
			fmt.Fprintf(&out, "    if (!is_array($result) || !array_is_list($result) || count($result) !== %d) {\n", len(outputs))
			fmt.Fprintf(&out, "        throw new \\UnexpectedValueException('%s returned invalid output data.');\n", function.Name)
			out.WriteString("    }\n")
			for i, output := range outputs {
				outputType := phpType(strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(output.Type), "*")))
				if outputType == "bool" || outputType == "int" || outputType == "float" || outputType == "string" {
					fmt.Fprintf(&out, "    if (!is_%s($result[%d])) {\n", phpTypeCheck(outputType), i)
					fmt.Fprintf(&out, "        throw new \\UnexpectedValueException('%s returned invalid %s output at index %d.');\n", function.Name, outputType, i)
					out.WriteString("    }\n")
				}
			}
			out.WriteString("    return [")
			for i := range outputs {
				if i > 0 {
					out.WriteString(", ")
				}
				fmt.Fprintf(&out, "$result[%d]", i)
			}
			out.WriteString("];\n")
		} else if function.Name == "NPC_GetAll" {
			fmt.Fprintf(&out, "    $result = %s;\n", call.String())
			out.WriteString("    if (!is_array($result)) {\n        throw new \\UnexpectedValueException('NPC_GetAll returned invalid output data.');\n    }\n")
			out.WriteString("    $npcs = [];\n    foreach ($result as $value) {\n        if (!is_int($value)) {\n            throw new \\UnexpectedValueException('NPC_GetAll returned invalid NPC data.');\n        }\n        $npcs[] = $value;\n    }\n    return $npcs;\n")
		} else if returnType == "void" {
			fmt.Fprintf(&out, "    %s;\n", call.String())
		} else if returnType == "bool" || returnType == "int" || returnType == "float" || returnType == "string" {
			fmt.Fprintf(&out, "    $result = %s;\n", call.String())
			fmt.Fprintf(&out, "    if (!is_%s($result)) {\n", phpTypeCheck(returnType))
			fmt.Fprintf(&out, "        throw new \\UnexpectedValueException('%s returned invalid %s data.');\n", function.Name, returnType)
			out.WriteString("    }\n    return $result;\n")
		} else {
			fmt.Fprintf(&out, "    return %s;\n", call.String())
		}
		out.WriteString("}\n\n")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create PHP output directory: %w", err)
	}
	if err := os.WriteFile(path, out.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write generated PHP API: %w", err)
	}
	return nil
}

func phpTypeCheck(phpType string) string {
	if phpType == "float" {
		return "float"
	}
	return phpType
}

func generateEvents(path string, m model.Model) error {
	var out bytes.Buffer
	out.WriteString("<?php\n\ndeclare(strict_types=1);\n\nnamespace Omp\\Event;\n\n// Code generated by tools/codegen. DO NOT EDIT.\n\nfinal class Events\n{\n")
	for _, event := range m.Events {
		name := strings.TrimPrefix(event.Name, "on")
		if name == event.Name {
			name = strings.TrimPrefix(event.Name, "On")
		}
		parameters := make([]string, len(event.Parameters))
		for i, parameter := range event.Parameters {
			parameters[i] = phpType(parameter.Type) + " $" + safePHPName(parameter.Name)
		}
		fallback := "true"
		if event.ReturnType == "false" {
			fallback = "false"
		}
		fmt.Fprintf(&out, "    /** Handler: function(%s); default result: %s. */\n", strings.Join(parameters, ", "), fallback)
		fmt.Fprintf(&out, "    public const %s = '%s';\n", strings.ToUpper(snake(name)), name)
	}
	out.WriteString("}\n")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create event output directory: %w", err)
	}
	if err := os.WriteFile(path, out.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write generated PHP events: %w", err)
	}
	return nil
}

func generateEventHandlers(path string, m model.Model) error {
	var out bytes.Buffer
	out.WriteString("<?php\n\ndeclare(strict_types=1);\n\nnamespace Omp\\Event;\n\n// Code generated by tools/codegen. DO NOT EDIT.\n\nfinal class Handlers\n{\n")
	for _, event := range m.Events {
		name := strings.TrimPrefix(event.Name, "on")
		if name == event.Name {
			name = strings.TrimPrefix(event.Name, "On")
		}
		parameters := make([]string, len(event.Parameters))
		for i, parameter := range event.Parameters {
			parameters[i] = phpType(parameter.Type)
		}
		fmt.Fprintf(&out, "    /** @param callable(%s): mixed $handler */\n", strings.Join(parameters, ", "))
		fmt.Fprintf(&out, "    public static function %s(callable $handler): void\n    {\n", lowerCamel(name))
		fmt.Fprintf(&out, "        \\Omp\\Server::on(Events::%s, $handler);\n", strings.ToUpper(snake(name)))
		out.WriteString("    }\n\n")
	}
	out.WriteString("}\n")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create event handler output directory: %w", err)
	}
	if err := os.WriteFile(path, out.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write generated PHP event handlers: %w", err)
	}
	return nil
}

func generatePublicAPI(outDir string, m model.Model) (int, error) {
	groups := make(map[string][]model.Function)
	for _, function := range m.Functions {
		if phpCallable(function) {
			groups[function.Group] = append(groups[function.Group], function)
		}
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return 0, fmt.Errorf("create public PHP API directory: %w", err)
	}
	count := 0
	for group, functions := range groups {
		className := publicGroupName(group)
		var out bytes.Buffer
		out.WriteString("<?php\n\ndeclare(strict_types=1);\n\nnamespace Omp\\Api;\n\n// Code generated by tools/codegen. DO NOT EDIT.\n\n")
		fmt.Fprintf(&out, "final class %s\n{\n", className)
		for _, function := range functions {
			method := strings.TrimPrefix(function.Name, function.Group+"_")
			method = lowerCamel(method)
			inputs := make([]model.Parameter, 0, len(function.Parameters))
			outputs := make([]model.Parameter, 0, len(function.Parameters))
			for _, parameter := range function.Parameters {
				if parameter.Output {
					outputs = append(outputs, parameter)
				} else {
					inputs = append(inputs, parameter)
				}
			}
			returnType := publicReturnType(function, outputs)
			if len(outputs) > 1 {
				parts := make([]string, len(outputs))
				for i, output := range outputs {
					parts[i] = phpType(strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(output.Type), "*")))
				}
				fmt.Fprintf(&out, "    /** @return array{%s} */\n", strings.Join(parts, ", "))
			} else if function.Name == "NPC_GetAll" {
				out.WriteString("    /** @return list<int> */\n")
			}
			fmt.Fprintf(&out, "    public static function %s(", method)
			for i, parameter := range inputs {
				if i > 0 {
					out.WriteString(", ")
				}
				fmt.Fprintf(&out, "%s $%s", phpType(parameter.Type), safePHPName(parameter.Name))
			}
			fmt.Fprintf(&out, "): %s\n    {\n", returnType)
			call := fmt.Sprintf("\\Omp\\Internal\\%s(", snake(function.Name))
			for i, parameter := range inputs {
				if i > 0 {
					call += ", "
				}
				call += "$" + safePHPName(parameter.Name)
			}
			call += ")"
			if returnType == "void" {
				fmt.Fprintf(&out, "        %s;\n", call)
			} else {
				cast := publicReturnCast(returnType)
				fmt.Fprintf(&out, "        return %s%s;\n", cast, call)
			}
			out.WriteString("    }\n\n")
			count++
		}
		out.WriteString("}\n")
		if err := os.WriteFile(filepath.Join(outDir, className+".php"), out.Bytes(), 0o644); err != nil {
			return 0, fmt.Errorf("write public PHP API group %s: %w", group, err)
		}
	}
	return count, nil
}

func publicGroupName(group string) string {
	switch group {
	case "Class":
		return "PlayerClass"
	case "Object":
		return "GameObject"
	default:
		return group
	}
}

func publicReturnType(function model.Function, outputs []model.Parameter) string {
	if function.Name == "NPC_GetAll" || len(outputs) > 1 {
		return "array"
	}
	if len(outputs) == 1 {
		return phpType(strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(outputs[0].Type), "*")))
	}
	return phpType(function.ReturnType)
}

func publicReturnCast(returnType string) string {
	switch returnType {
	case "bool", "int", "float", "string", "array":
		return "(" + returnType + ") "
	default:
		return ""
	}
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	runes := []rune(value)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func lowerCamel(value string) string {
	words := strings.Split(snake(value), "_")
	for i := 1; i < len(words); i++ {
		words[i] = strings.ToUpper(words[i][:1]) + words[i][1:]
	}
	return strings.Join(words, "")
}

func phpCallable(f model.Function) bool {
	if f.Group == "Component" || f.Group == "Event" {
		return false
	}
	for _, p := range f.Parameters {
		t := strings.TrimSpace(p.Type)
		if strings.Contains(t, "**") {
			return false
		}
	}
	return true
}

func phpType(cType string) string {
	t := strings.TrimSpace(cType)
	switch t {
	case "bool":
		return "bool"
	case "float", "double":
		return "float"
	case "const char*", "struct CAPIStringView", "CAPIStringView", "CAPIStringBuffer":
		return "string"
	case "void":
		return "void"
	case "void*":
		return "int"
	default:
		if strings.Contains(t, "int") || strings.HasPrefix(t, "uint") {
			return "int"
		}
		return "mixed"
	}
}

func snake(name string) string {
	name = acronymBoundary.ReplaceAllString(name, `${1}_${2}`)
	name = wordBoundary.ReplaceAllString(name, `${1}_${2}`)
	return strings.ToLower(name)
}

func safePHPName(name string) string {
	if name == "class" || name == "function" || name == "match" {
		return name + "Value"
	}
	if name == "" {
		return "argument"
	}
	runes := []rune(name)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}
