<?php

declare(strict_types=1);

namespace Omp\Api;

// Code generated by tools/codegen. DO NOT EDIT.

final class Config
{
    public static function getAsBool(string $cvar): bool
    {
        return \Omp\Internal\config_get_as_bool($cvar);
    }

    public static function getAsFloat(string $cvar): float
    {
        return \Omp\Internal\config_get_as_float($cvar);
    }

    public static function getAsInt(string $cvar): int
    {
        return \Omp\Internal\config_get_as_int($cvar);
    }

    public static function getAsString(string $cvar): string
    {
        return \Omp\Internal\config_get_as_string($cvar);
    }

}
