<?php

declare(strict_types=1);

namespace Omp\Api;

// Code generated by tools/codegen. DO NOT EDIT.

final class Dialog
{
    public static function hide(int $player): bool
    {
        return (bool) \Omp\Internal\dialog_hide($player);
    }

    public static function show(int $player, int $dialog, int $style, string $title, string $body, string $button1, string $button2): bool
    {
        return (bool) \Omp\Internal\dialog_show($player, $dialog, $style, $title, $body, $button1, $button2);
    }

}
