<?php

declare(strict_types=1);

namespace Omp\Api;

// Code generated by tools/codegen. DO NOT EDIT.

final class PlayerClass
{
    public static function add(int $team, int $skin, float $x, float $y, float $z, float $angle, int $weapon1, int $ammo1, int $weapon2, int $ammo2, int $weapon3, int $ammo3): int
    {
        return (int) \Omp\Internal\class_add($team, $skin, $x, $y, $z, $angle, $weapon1, $ammo1, $weapon2, $ammo2, $weapon3, $ammo3);
    }

    public static function count(): int
    {
        return (int) \Omp\Internal\class_count();
    }

    public static function edit(int $classptr, int $teamid, int $skin, float $x, float $y, float $z, float $angle, int $weapon1, int $ammo1, int $weapon2, int $ammo2, int $weapon3, int $ammo3): bool
    {
        return (bool) \Omp\Internal\class_edit($classptr, $teamid, $skin, $x, $y, $z, $angle, $weapon1, $ammo1, $weapon2, $ammo2, $weapon3, $ammo3);
    }

    public static function fromId(int $classid): int
    {
        return (int) \Omp\Internal\class_from_id($classid);
    }

    /** @return array{int, int, float, float, float, float, int, int, int, int, int, int} */
    public static function getData(int $classptr): array
    {
        return (array) \Omp\Internal\class_get_data($classptr);
    }

    public static function getId(int $cls): int
    {
        return (int) \Omp\Internal\class_get_id($cls);
    }

}
