<?php

declare(strict_types=1);

namespace Omp\Api;

// Code generated by tools/codegen. DO NOT EDIT.

final class Player
{
    public static function allowTeleport(int $player, bool $allow): bool
    {
        return (bool) \Omp\Internal\player_allow_teleport($player, $allow);
    }

    public static function allowWeapons(int $player, bool $allow): bool
    {
        return (bool) \Omp\Internal\player_allow_weapons($player, $allow);
    }

    public static function applyAnimation(int $player, string $animlib, string $animname, float $delta, bool $loop, bool $lockX, bool $lockY, bool $freeze, int $time, int $sync): bool
    {
        return (bool) \Omp\Internal\player_apply_animation($player, $animlib, $animname, $delta, $loop, $lockX, $lockY, $freeze, $time, $sync);
    }

    public static function areWeaponsAllowed(int $player): bool
    {
        return (bool) \Omp\Internal\player_are_weapons_allowed($player);
    }

    public static function attachCameraToObject(int $player, int $object): bool
    {
        return (bool) \Omp\Internal\player_attach_camera_to_object($player, $object);
    }

    public static function attachCameraToPlayerObject(int $player, int $object): bool
    {
        return (bool) \Omp\Internal\player_attach_camera_to_player_object($player, $object);
    }

    public static function ban(int $player): bool
    {
        return (bool) \Omp\Internal\player_ban($player);
    }

    public static function banEx(int $player, string $reason): bool
    {
        return (bool) \Omp\Internal\player_ban_ex($player, $reason);
    }

    public static function cancelSelectTextDraw(int $player): bool
    {
        return (bool) \Omp\Internal\player_cancel_select_text_draw($player);
    }

    public static function clearAnimations(int $player, int $syncType): bool
    {
        return (bool) \Omp\Internal\player_clear_animations($player, $syncType);
    }

    public static function clearWorldBounds(int $player): bool
    {
        return (bool) \Omp\Internal\player_clear_world_bounds($player);
    }

    public static function createExplosion(int $player, float $x, float $y, float $z, int $type, float $radius): bool
    {
        return (bool) \Omp\Internal\player_create_explosion($player, $x, $y, $z, $type, $radius);
    }

    public static function disableRemoteVehicleCollisions(int $player, bool $disable): bool
    {
        return (bool) \Omp\Internal\player_disable_remote_vehicle_collisions($player, $disable);
    }

    public static function editAttachedObject(int $player, int $index): bool
    {
        return (bool) \Omp\Internal\player_edit_attached_object($player, $index);
    }

    public static function enableCameraTarget(int $player, bool $enable): bool
    {
        return (bool) \Omp\Internal\player_enable_camera_target($player, $enable);
    }

    public static function enableStuntBonus(int $player, bool $enable): bool
    {
        return (bool) \Omp\Internal\player_enable_stunt_bonus($player, $enable);
    }

    public static function forceClassSelection(int $player): bool
    {
        return (bool) \Omp\Internal\player_force_class_selection($player);
    }

    public static function fromId(int $playerid): int
    {
        return (int) \Omp\Internal\player_from_id($playerid);
    }

    public static function gpci(int $player): string
    {
        return (string) \Omp\Internal\player_gpci($player);
    }

    public static function getAnimationFlags(int $player): int
    {
        return (int) \Omp\Internal\player_get_animation_flags($player);
    }

    public static function getAnimationIndex(int $player): int
    {
        return (int) \Omp\Internal\player_get_animation_index($player);
    }

    /** @return array{string, string} */
    public static function getAnimationName(int $index): array
    {
        return (array) \Omp\Internal\player_get_animation_name($index);
    }

    public static function getArmor(int $player): float
    {
        return (float) \Omp\Internal\player_get_armor($player);
    }

    /** @return array{int, int, float, float, float, float, float, float, float, float, float, int, int} */
    public static function getAttachedObject(int $player, int $index): array
    {
        return (array) \Omp\Internal\player_get_attached_object($player, $index);
    }

    public static function getBuildingsRemoved(int $player): int
    {
        return (int) \Omp\Internal\player_get_buildings_removed($player);
    }

    public static function getCameraAspectRatio(int $player): float
    {
        return (float) \Omp\Internal\player_get_camera_aspect_ratio($player);
    }

    /** @return array{float, float, float} */
    public static function getCameraFrontVector(int $player): array
    {
        return (array) \Omp\Internal\player_get_camera_front_vector($player);
    }

    public static function getCameraMode(int $player): int
    {
        return (int) \Omp\Internal\player_get_camera_mode($player);
    }

    /** @return array{float, float, float} */
    public static function getCameraPos(int $player): array
    {
        return (array) \Omp\Internal\player_get_camera_pos($player);
    }

    public static function getCameraTargetActor(int $player): int
    {
        return (int) \Omp\Internal\player_get_camera_target_actor($player);
    }

    public static function getCameraTargetObject(int $player): int
    {
        return (int) \Omp\Internal\player_get_camera_target_object($player);
    }

    public static function getCameraTargetPlayer(int $player): int
    {
        return (int) \Omp\Internal\player_get_camera_target_player($player);
    }

    public static function getCameraTargetPlayerObject(int $player): int
    {
        return (int) \Omp\Internal\player_get_camera_target_player_object($player);
    }

    public static function getCameraTargetVehicle(int $player): int
    {
        return (int) \Omp\Internal\player_get_camera_target_vehicle($player);
    }

    public static function getCameraZoom(int $player): float
    {
        return (float) \Omp\Internal\player_get_camera_zoom($player);
    }

    public static function getColor(int $player): int
    {
        return (int) \Omp\Internal\player_get_color($player);
    }

    public static function getCustomSkin(int $player): int
    {
        return (int) \Omp\Internal\player_get_custom_skin($player);
    }

    public static function getDefaultColor(int $player): int
    {
        return (int) \Omp\Internal\player_get_default_color($player);
    }

    public static function getDialog(int $player): int
    {
        return (int) \Omp\Internal\player_get_dialog($player);
    }

    /** @return array{int, int, string, string, string, string} */
    public static function getDialogData(int $player): array
    {
        return (array) \Omp\Internal\player_get_dialog_data($player);
    }

    public static function getDistanceFromPoint(int $player, float $x, float $y, float $z): float
    {
        return (float) \Omp\Internal\player_get_distance_from_point($player, $x, $y, $z);
    }

    public static function getDrunkLevel(int $player): int
    {
        return (int) \Omp\Internal\player_get_drunk_level($player);
    }

    public static function getFacingAngle(int $player): float
    {
        return (float) \Omp\Internal\player_get_facing_angle($player);
    }

    public static function getFightingStyle(int $player): int
    {
        return (int) \Omp\Internal\player_get_fighting_style($player);
    }

    /** @return array{string, int, int} */
    public static function getGameText(int $player, int $style): array
    {
        return (array) \Omp\Internal\player_get_game_text($player, $style);
    }

    public static function getGhostMode(int $player): bool
    {
        return (bool) \Omp\Internal\player_get_ghost_mode($player);
    }

    public static function getGravity(int $player): float
    {
        return (float) \Omp\Internal\player_get_gravity($player);
    }

    public static function getHealth(int $player): float
    {
        return (float) \Omp\Internal\player_get_health($player);
    }

    public static function getHydraReactorAngle(int $player): int
    {
        return (int) \Omp\Internal\player_get_hydra_reactor_angle($player);
    }

    public static function getId(int $player): int
    {
        return (int) \Omp\Internal\player_get_id($player);
    }

    public static function getInterior(int $player): int
    {
        return (int) \Omp\Internal\player_get_interior($player);
    }

    public static function getIp(int $player): string
    {
        return (string) \Omp\Internal\player_get_ip($player);
    }

    /** @return array{int, int, int} */
    public static function getKeys(int $player): array
    {
        return (array) \Omp\Internal\player_get_keys($player);
    }

    public static function getLandingGearState(int $player): int
    {
        return (int) \Omp\Internal\player_get_landing_gear_state($player);
    }

    /** @return array{float, float, float, float, float, float} */
    public static function getLastShotVectors(int $player): array
    {
        return (array) \Omp\Internal\player_get_last_shot_vectors($player);
    }

    public static function getMarkerForPlayer(int $player, int $other): int
    {
        return (int) \Omp\Internal\player_get_marker_for_player($player, $other);
    }

    public static function getMenu(int $player): int
    {
        return (int) \Omp\Internal\player_get_menu($player);
    }

    public static function getMoney(int $player): int
    {
        return (int) \Omp\Internal\player_get_money($player);
    }

    public static function getName(int $player): string
    {
        return (string) \Omp\Internal\player_get_name($player);
    }

    public static function getNetworkStats(int $player): string
    {
        return (string) \Omp\Internal\player_get_network_stats($player);
    }

    public static function getPing(int $player): int
    {
        return (int) \Omp\Internal\player_get_ping($player);
    }

    public static function getPlayerAmmo(int $player): int
    {
        return (int) \Omp\Internal\player_get_player_ammo($player);
    }

    public static function getPlayerSpectateId(int $player): int
    {
        return (int) \Omp\Internal\player_get_player_spectate_id($player);
    }

    /** @return array{float, float, float} */
    public static function getPos(int $player): array
    {
        return (array) \Omp\Internal\player_get_pos($player);
    }

    public static function getRawIp(int $player): int
    {
        return (int) \Omp\Internal\player_get_raw_ip($player);
    }

    /** @return array{float, float, float, float} */
    public static function getRotationQuat(int $player): array
    {
        return (array) \Omp\Internal\player_get_rotation_quat($player);
    }

    public static function getScore(int $player): int
    {
        return (int) \Omp\Internal\player_get_score($player);
    }

    public static function getSirenState(int $player): int
    {
        return (int) \Omp\Internal\player_get_siren_state($player);
    }

    public static function getSkillLevel(int $player, int $skill): int
    {
        return (int) \Omp\Internal\player_get_skill_level($player, $skill);
    }

    public static function getSkin(int $player): int
    {
        return (int) \Omp\Internal\player_get_skin($player);
    }

    /** @return array{int, int, float, float, float, float, int, int, int, int, int, int} */
    public static function getSpawnInfo(int $player): array
    {
        return (array) \Omp\Internal\player_get_spawn_info($player);
    }

    public static function getSpecialAction(int $player): int
    {
        return (int) \Omp\Internal\player_get_special_action($player);
    }

    public static function getSpectateType(int $player): int
    {
        return (int) \Omp\Internal\player_get_spectate_type($player);
    }

    public static function getState(int $player): int
    {
        return (int) \Omp\Internal\player_get_state($player);
    }

    public static function getSurfingObject(int $player): int
    {
        return (int) \Omp\Internal\player_get_surfing_object($player);
    }

    /** @return array{float, float, float} */
    public static function getSurfingOffsets(int $player): array
    {
        return (array) \Omp\Internal\player_get_surfing_offsets($player);
    }

    public static function getSurfingPlayerObject(int $player): int
    {
        return (int) \Omp\Internal\player_get_surfing_player_object($player);
    }

    public static function getSurfingVehicle(int $player): int
    {
        return (int) \Omp\Internal\player_get_surfing_vehicle($player);
    }

    public static function getTargetActor(int $player): int
    {
        return (int) \Omp\Internal\player_get_target_actor($player);
    }

    public static function getTargetPlayer(int $player): int
    {
        return (int) \Omp\Internal\player_get_target_player($player);
    }

    public static function getTeam(int $player): int
    {
        return (int) \Omp\Internal\player_get_team($player);
    }

    /** @return array{int, int} */
    public static function getTime(int $player): array
    {
        return (array) \Omp\Internal\player_get_time($player);
    }

    public static function getTrainSpeed(int $player): float
    {
        return (float) \Omp\Internal\player_get_train_speed($player);
    }

    public static function getVehicleId(int $player): int
    {
        return (int) \Omp\Internal\player_get_vehicle_id($player);
    }

    public static function getVehicleSeat(int $player): int
    {
        return (int) \Omp\Internal\player_get_vehicle_seat($player);
    }

    /** @return array{float, float, float} */
    public static function getVelocity(int $player): array
    {
        return (array) \Omp\Internal\player_get_velocity($player);
    }

    public static function getVersion(int $player): string
    {
        return (string) \Omp\Internal\player_get_version($player);
    }

    public static function getVirtualWorld(int $player): int
    {
        return (int) \Omp\Internal\player_get_virtual_world($player);
    }

    public static function getWantedLevel(int $player): int
    {
        return (int) \Omp\Internal\player_get_wanted_level($player);
    }

    public static function getWeapon(int $player): int
    {
        return (int) \Omp\Internal\player_get_weapon($player);
    }

    /** @return array{int, int} */
    public static function getWeaponData(int $player, int $slot): array
    {
        return (array) \Omp\Internal\player_get_weapon_data($player, $slot);
    }

    public static function getWeaponState(int $player): int
    {
        return (int) \Omp\Internal\player_get_weapon_state($player);
    }

    public static function getWeather(int $player): int
    {
        return (int) \Omp\Internal\player_get_weather($player);
    }

    /** @return array{float, float, float, float} */
    public static function getWorldBounds(int $player): array
    {
        return (array) \Omp\Internal\player_get_world_bounds($player);
    }

    public static function getZAim(int $player): float
    {
        return (float) \Omp\Internal\player_get_z_aim($player);
    }

    public static function giveMoney(int $player, int $amount): bool
    {
        return (bool) \Omp\Internal\player_give_money($player, $amount);
    }

    public static function giveWeapon(int $player, int $weapon, int $ammo): bool
    {
        return (bool) \Omp\Internal\player_give_weapon($player, $weapon, $ammo);
    }

    public static function hasClock(int $player): bool
    {
        return (bool) \Omp\Internal\player_has_clock($player);
    }

    public static function hasGameText(int $player, int $style): bool
    {
        return (bool) \Omp\Internal\player_has_game_text($player, $style);
    }

    public static function hideGameText(int $player, int $style): bool
    {
        return (bool) \Omp\Internal\player_hide_game_text($player, $style);
    }

    public static function interpolateCameraLookAt(int $player, float $from_x, float $from_y, float $from_z, float $to_x, float $to_y, float $to_z, int $time, int $cut): bool
    {
        return (bool) \Omp\Internal\player_interpolate_camera_look_at($player, $from_x, $from_y, $from_z, $to_x, $to_y, $to_z, $time, $cut);
    }

    public static function interpolateCameraPos(int $player, float $from_x, float $from_y, float $from_z, float $to_x, float $to_y, float $to_z, int $time, int $cut): bool
    {
        return (bool) \Omp\Internal\player_interpolate_camera_pos($player, $from_x, $from_y, $from_z, $to_x, $to_y, $to_z, $time, $cut);
    }

    public static function isAdmin(int $player): bool
    {
        return (bool) \Omp\Internal\player_is_admin($player);
    }

    public static function isCameraTargetEnabled(int $player): bool
    {
        return (bool) \Omp\Internal\player_is_camera_target_enabled($player);
    }

    public static function isControllable(int $player): bool
    {
        return (bool) \Omp\Internal\player_is_controllable($player);
    }

    public static function isCuffed(int $player): bool
    {
        return (bool) \Omp\Internal\player_is_cuffed($player);
    }

    public static function isInAnyVehicle(int $player): bool
    {
        return (bool) \Omp\Internal\player_is_in_any_vehicle($player);
    }

    public static function isInDriveByMode(int $player): bool
    {
        return (bool) \Omp\Internal\player_is_in_drive_by_mode($player);
    }

    public static function isInModShop(int $player): bool
    {
        return (bool) \Omp\Internal\player_is_in_mod_shop($player);
    }

    public static function isInRangeOfPoint(int $player, float $range, float $x, float $y, float $z): bool
    {
        return (bool) \Omp\Internal\player_is_in_range_of_point($player, $range, $x, $y, $z);
    }

    public static function isInVehicle(int $player, int $targetVehicle): bool
    {
        return (bool) \Omp\Internal\player_is_in_vehicle($player, $targetVehicle);
    }

    public static function isNpc(int $player): bool
    {
        return (bool) \Omp\Internal\player_is_npc($player);
    }

    public static function isPlayerAttachedObjectSlotUsed(int $player, int $index): bool
    {
        return (bool) \Omp\Internal\player_is_player_attached_object_slot_used($player, $index);
    }

    public static function isPlayerUsingOfficialClient(int $player): bool
    {
        return (bool) \Omp\Internal\player_is_player_using_official_client($player);
    }

    public static function isSpawned(int $player): bool
    {
        return (bool) \Omp\Internal\player_is_spawned($player);
    }

    public static function isStreamedIn(int $player, int $other): bool
    {
        return (bool) \Omp\Internal\player_is_streamed_in($player, $other);
    }

    public static function isTeleportAllowed(int $player): bool
    {
        return (bool) \Omp\Internal\player_is_teleport_allowed($player);
    }

    public static function isUsingOmp(int $player): bool
    {
        return (bool) \Omp\Internal\player_is_using_omp($player);
    }

    public static function isWidescreenToggled(int $player): bool
    {
        return (bool) \Omp\Internal\player_is_widescreen_toggled($player);
    }

    public static function kick(int $player): bool
    {
        return (bool) \Omp\Internal\player_kick($player);
    }

    public static function netStatsBytesReceived(int $player): int
    {
        return (int) \Omp\Internal\player_net_stats_bytes_received($player);
    }

    public static function netStatsBytesSent(int $player): int
    {
        return (int) \Omp\Internal\player_net_stats_bytes_sent($player);
    }

    public static function netStatsConnectionStatus(int $player): int
    {
        return (int) \Omp\Internal\player_net_stats_connection_status($player);
    }

    public static function netStatsGetConnectedTime(int $player): int
    {
        return (int) \Omp\Internal\player_net_stats_get_connected_time($player);
    }

    public static function netStatsGetIpPort(int $player): string
    {
        return (string) \Omp\Internal\player_net_stats_get_ip_port($player);
    }

    public static function netStatsMessagesReceived(int $player): int
    {
        return (int) \Omp\Internal\player_net_stats_messages_received($player);
    }

    public static function netStatsMessagesRecvPerSecond(int $player): int
    {
        return (int) \Omp\Internal\player_net_stats_messages_recv_per_second($player);
    }

    public static function netStatsMessagesSent(int $player): int
    {
        return (int) \Omp\Internal\player_net_stats_messages_sent($player);
    }

    public static function netStatsPacketLossPercent(int $player): float
    {
        return (float) \Omp\Internal\player_net_stats_packet_loss_percent($player);
    }

    public static function playAudioStream(int $player, string $url, float $x, float $y, float $z, float $distance, bool $usePos): bool
    {
        return (bool) \Omp\Internal\player_play_audio_stream($player, $url, $x, $y, $z, $distance, $usePos);
    }

    public static function playCrimeReport(int $player, int $suspect, int $crime): bool
    {
        return (bool) \Omp\Internal\player_play_crime_report($player, $suspect, $crime);
    }

    public static function playGameSound(int $player, int $sound, float $x, float $y, float $z): bool
    {
        return (bool) \Omp\Internal\player_play_game_sound($player, $sound, $x, $y, $z);
    }

    public static function putInVehicle(int $player, int $vehicle, int $seat): bool
    {
        return (bool) \Omp\Internal\player_put_in_vehicle($player, $vehicle, $seat);
    }

    public static function removeAttachedObject(int $player, int $index): bool
    {
        return (bool) \Omp\Internal\player_remove_attached_object($player, $index);
    }

    public static function removeBuilding(int $player, int $model, float $x, float $y, float $z, float $radius): bool
    {
        return (bool) \Omp\Internal\player_remove_building($player, $model, $x, $y, $z, $radius);
    }

    public static function removeFromVehicle(int $player, bool $force): bool
    {
        return (bool) \Omp\Internal\player_remove_from_vehicle($player, $force);
    }

    public static function removeMapIcon(int $player, int $icon): bool
    {
        return (bool) \Omp\Internal\player_remove_map_icon($player, $icon);
    }

    public static function removeWeapon(int $player, int $weapon): bool
    {
        return (bool) \Omp\Internal\player_remove_weapon($player, $weapon);
    }

    public static function resetMoney(int $player): bool
    {
        return (bool) \Omp\Internal\player_reset_money($player);
    }

    public static function resetWeapons(int $player): bool
    {
        return (bool) \Omp\Internal\player_reset_weapons($player);
    }

    public static function selectTextDraw(int $player, int $hoverColour): bool
    {
        return (bool) \Omp\Internal\player_select_text_draw($player, $hoverColour);
    }

    public static function sendClientCheck(int $player, int $actionType, int $address, int $offset, int $count): bool
    {
        return (bool) \Omp\Internal\player_send_client_check($player, $actionType, $address, $offset, $count);
    }

    public static function sendClientMessage(int $player, int $color, string $text): bool
    {
        return (bool) \Omp\Internal\player_send_client_message($player, $color, $text);
    }

    public static function sendDeathMessage(int $player, int $killer, int $killee, int $weapon): bool
    {
        return (bool) \Omp\Internal\player_send_death_message($player, $killer, $killee, $weapon);
    }

    public static function sendMessageToPlayer(int $player, int $sender, string $message): bool
    {
        return (bool) \Omp\Internal\player_send_message_to_player($player, $sender, $message);
    }

    public static function setAdmin(int $player, bool $set): bool
    {
        return (bool) \Omp\Internal\player_set_admin($player, $set);
    }

    public static function setAmmo(int $player, int $id, int $ammo): bool
    {
        return (bool) \Omp\Internal\player_set_ammo($player, $id, $ammo);
    }

    public static function setArmedWeapon(int $player, int $weapon): bool
    {
        return (bool) \Omp\Internal\player_set_armed_weapon($player, $weapon);
    }

    public static function setArmor(int $player, float $armor): bool
    {
        return (bool) \Omp\Internal\player_set_armor($player, $armor);
    }

    public static function setAttachedObject(int $player, int $index, int $modelid, int $bone, float $offsetX, float $offsetY, float $offsetZ, float $rotationX, float $rotationY, float $rotationZ, float $scaleX, float $scaleY, float $scaleZ, int $materialcolor1, int $materialcolor2): bool
    {
        return (bool) \Omp\Internal\player_set_attached_object($player, $index, $modelid, $bone, $offsetX, $offsetY, $offsetZ, $rotationX, $rotationY, $rotationZ, $scaleX, $scaleY, $scaleZ, $materialcolor1, $materialcolor2);
    }

    public static function setCameraBehind(int $player): bool
    {
        return (bool) \Omp\Internal\player_set_camera_behind($player);
    }

    public static function setCameraLookAt(int $player, float $x, float $y, float $z, int $cutType): bool
    {
        return (bool) \Omp\Internal\player_set_camera_look_at($player, $x, $y, $z, $cutType);
    }

    public static function setCameraPos(int $player, float $x, float $y, float $z): bool
    {
        return (bool) \Omp\Internal\player_set_camera_pos($player, $x, $y, $z);
    }

    public static function setChatBubble(int $player, string $text, int $color, float $drawdistance, int $expiretime): bool
    {
        return (bool) \Omp\Internal\player_set_chat_bubble($player, $text, $color, $drawdistance, $expiretime);
    }

    public static function setColor(int $player, int $color): bool
    {
        return (bool) \Omp\Internal\player_set_color($player, $color);
    }

    public static function setDrunkLevel(int $player, int $level): bool
    {
        return (bool) \Omp\Internal\player_set_drunk_level($player, $level);
    }

    public static function setFacingAngle(int $player, float $angle): bool
    {
        return (bool) \Omp\Internal\player_set_facing_angle($player, $angle);
    }

    public static function setFightingStyle(int $player, int $style): bool
    {
        return (bool) \Omp\Internal\player_set_fighting_style($player, $style);
    }

    public static function setGravity(int $player, float $gravity): bool
    {
        return (bool) \Omp\Internal\player_set_gravity($player, $gravity);
    }

    public static function setHealth(int $player, float $health): bool
    {
        return (bool) \Omp\Internal\player_set_health($player, $health);
    }

    public static function setInterior(int $player, int $interior): bool
    {
        return (bool) \Omp\Internal\player_set_interior($player, $interior);
    }

    public static function setMapIcon(int $player, int $iconID, float $x, float $y, float $z, int $type, int $color, int $style): bool
    {
        return (bool) \Omp\Internal\player_set_map_icon($player, $iconID, $x, $y, $z, $type, $color, $style);
    }

    public static function setMarkerForPlayer(int $player, int $other, int $color): bool
    {
        return (bool) \Omp\Internal\player_set_marker_for_player($player, $other, $color);
    }

    public static function setName(int $player, string $name): int
    {
        return (int) \Omp\Internal\player_set_name($player, $name);
    }

    public static function setPos(int $player, float $x, float $y, float $z): bool
    {
        return (bool) \Omp\Internal\player_set_pos($player, $x, $y, $z);
    }

    public static function setPosFindZ(int $player, float $x, float $y, float $z): bool
    {
        return (bool) \Omp\Internal\player_set_pos_find_z($player, $x, $y, $z);
    }

    public static function setScore(int $player, int $score): bool
    {
        return (bool) \Omp\Internal\player_set_score($player, $score);
    }

    public static function setShopName(int $player, string $name): bool
    {
        return (bool) \Omp\Internal\player_set_shop_name($player, $name);
    }

    public static function setSkillLevel(int $player, int $weapon, int $level): bool
    {
        return (bool) \Omp\Internal\player_set_skill_level($player, $weapon, $level);
    }

    public static function setSkin(int $player, int $skin): bool
    {
        return (bool) \Omp\Internal\player_set_skin($player, $skin);
    }

    public static function setSpawnInfo(int $player, int $team, int $skin, float $x, float $y, float $z, float $angle, int $weapon1, int $ammo1, int $weapon2, int $ammo2, int $weapon3, int $ammo3): bool
    {
        return (bool) \Omp\Internal\player_set_spawn_info($player, $team, $skin, $x, $y, $z, $angle, $weapon1, $ammo1, $weapon2, $ammo2, $weapon3, $ammo3);
    }

    public static function setSpecialAction(int $player, int $action): bool
    {
        return (bool) \Omp\Internal\player_set_special_action($player, $action);
    }

    public static function setTeam(int $player, int $team): bool
    {
        return (bool) \Omp\Internal\player_set_team($player, $team);
    }

    public static function setTime(int $player, int $hour, int $minute): bool
    {
        return (bool) \Omp\Internal\player_set_time($player, $hour, $minute);
    }

    public static function setVelocity(int $player, float $x, float $y, float $z): bool
    {
        return (bool) \Omp\Internal\player_set_velocity($player, $x, $y, $z);
    }

    public static function setVirtualWorld(int $player, int $vw): bool
    {
        return (bool) \Omp\Internal\player_set_virtual_world($player, $vw);
    }

    public static function setWantedLevel(int $player, int $level): bool
    {
        return (bool) \Omp\Internal\player_set_wanted_level($player, $level);
    }

    public static function setWeather(int $player, int $weather): bool
    {
        return (bool) \Omp\Internal\player_set_weather($player, $weather);
    }

    public static function setWorldBounds(int $player, float $xMax, float $xMin, float $yMax, float $yMin): bool
    {
        return (bool) \Omp\Internal\player_set_world_bounds($player, $xMax, $xMin, $yMax, $yMin);
    }

    public static function showGameText(int $player, string $text, int $time, int $style): bool
    {
        return (bool) \Omp\Internal\player_show_game_text($player, $text, $time, $style);
    }

    public static function showNameTagForPlayer(int $player, int $other, bool $enable): bool
    {
        return (bool) \Omp\Internal\player_show_name_tag_for_player($player, $other, $enable);
    }

    public static function spawn(int $player): bool
    {
        return (bool) \Omp\Internal\player_spawn($player);
    }

    public static function spectatePlayer(int $player, int $target, int $mode): bool
    {
        return (bool) \Omp\Internal\player_spectate_player($player, $target, $mode);
    }

    public static function spectateVehicle(int $player, int $target, int $mode): bool
    {
        return (bool) \Omp\Internal\player_spectate_vehicle($player, $target, $mode);
    }

    public static function stopAudioStream(int $player): bool
    {
        return (bool) \Omp\Internal\player_stop_audio_stream($player);
    }

    public static function toggleClock(int $player, bool $enable): bool
    {
        return (bool) \Omp\Internal\player_toggle_clock($player, $enable);
    }

    public static function toggleControllable(int $player, bool $enable): bool
    {
        return (bool) \Omp\Internal\player_toggle_controllable($player, $enable);
    }

    public static function toggleGhostMode(int $player, bool $toggle): bool
    {
        return (bool) \Omp\Internal\player_toggle_ghost_mode($player, $toggle);
    }

    public static function toggleSpectating(int $player, bool $enable): bool
    {
        return (bool) \Omp\Internal\player_toggle_spectating($player, $enable);
    }

    public static function toggleWidescreen(int $player, bool $enable): bool
    {
        return (bool) \Omp\Internal\player_toggle_widescreen($player, $enable);
    }

}
