<?php

declare(strict_types=1);

namespace Omp\Api;

// Code generated by tools/codegen. DO NOT EDIT.

final class PlayerTextDraw
{
    public static function create(int $player, float $x, float $y, string $text): int
    {
        return (int) \Omp\Internal\player_text_draw_create($player, $x, $y, $text);
    }

    public static function destroy(int $player, int $textdraw): bool
    {
        return (bool) \Omp\Internal\player_text_draw_destroy($player, $textdraw);
    }

    public static function fromId(int $player, int $textdrawid): int
    {
        return (int) \Omp\Internal\player_text_draw_from_id($player, $textdrawid);
    }

    public static function getAlignment(int $player, int $textdraw): int
    {
        return (int) \Omp\Internal\player_text_draw_get_alignment($player, $textdraw);
    }

    public static function getBackgroundColor(int $player, int $textdraw): int
    {
        return (int) \Omp\Internal\player_text_draw_get_background_color($player, $textdraw);
    }

    public static function getBoxColor(int $player, int $textdraw): int
    {
        return (int) \Omp\Internal\player_text_draw_get_box_color($player, $textdraw);
    }

    public static function getColor(int $player, int $textdraw): int
    {
        return (int) \Omp\Internal\player_text_draw_get_color($player, $textdraw);
    }

    public static function getFont(int $player, int $textdraw): int
    {
        return (int) \Omp\Internal\player_text_draw_get_font($player, $textdraw);
    }

    public static function getId(int $player, int $textdraw): int
    {
        return (int) \Omp\Internal\player_text_draw_get_id($player, $textdraw);
    }

    /** @return array{float, float} */
    public static function getLetterSize(int $player, int $textdraw): array
    {
        return (array) \Omp\Internal\player_text_draw_get_letter_size($player, $textdraw);
    }

    public static function getOutline(int $player, int $textdraw): int
    {
        return (int) \Omp\Internal\player_text_draw_get_outline($player, $textdraw);
    }

    /** @return array{float, float} */
    public static function getPos(int $player, int $textdraw): array
    {
        return (array) \Omp\Internal\player_text_draw_get_pos($player, $textdraw);
    }

    public static function getPreviewModel(int $player, int $textdraw): int
    {
        return (int) \Omp\Internal\player_text_draw_get_preview_model($player, $textdraw);
    }

    /** @return array{float, float, float, float} */
    public static function getPreviewRot(int $player, int $textdraw): array
    {
        return (array) \Omp\Internal\player_text_draw_get_preview_rot($player, $textdraw);
    }

    /** @return array{int, int} */
    public static function getPreviewVehColor(int $player, int $textdraw): array
    {
        return (array) \Omp\Internal\player_text_draw_get_preview_veh_color($player, $textdraw);
    }

    public static function getShadow(int $player, int $textdraw): int
    {
        return (int) \Omp\Internal\player_text_draw_get_shadow($player, $textdraw);
    }

    public static function getString(int $player, int $textdraw): string
    {
        return (string) \Omp\Internal\player_text_draw_get_string($player, $textdraw);
    }

    /** @return array{float, float} */
    public static function getTextSize(int $player, int $textdraw): array
    {
        return (array) \Omp\Internal\player_text_draw_get_text_size($player, $textdraw);
    }

    public static function hide(int $player, int $textdraw): bool
    {
        return (bool) \Omp\Internal\player_text_draw_hide($player, $textdraw);
    }

    public static function isBox(int $player, int $textdraw): bool
    {
        return (bool) \Omp\Internal\player_text_draw_is_box($player, $textdraw);
    }

    public static function isProportional(int $player, int $textdraw): bool
    {
        return (bool) \Omp\Internal\player_text_draw_is_proportional($player, $textdraw);
    }

    public static function isSelectable(int $player, int $textdraw): bool
    {
        return (bool) \Omp\Internal\player_text_draw_is_selectable($player, $textdraw);
    }

    public static function isValid(int $player, int $textdraw): bool
    {
        return (bool) \Omp\Internal\player_text_draw_is_valid($player, $textdraw);
    }

    public static function isVisible(int $player, int $textdraw): bool
    {
        return (bool) \Omp\Internal\player_text_draw_is_visible($player, $textdraw);
    }

    public static function setAlignment(int $player, int $textdraw, int $alignment): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_alignment($player, $textdraw, $alignment);
    }

    public static function setBackgroundColor(int $player, int $textdraw, int $color): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_background_color($player, $textdraw, $color);
    }

    public static function setBoxColor(int $player, int $textdraw, int $color): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_box_color($player, $textdraw, $color);
    }

    public static function setColor(int $player, int $textdraw, int $color): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_color($player, $textdraw, $color);
    }

    public static function setFont(int $player, int $textdraw, int $font): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_font($player, $textdraw, $font);
    }

    public static function setLetterSize(int $player, int $textdraw, float $x, float $y): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_letter_size($player, $textdraw, $x, $y);
    }

    public static function setOutline(int $player, int $textdraw, int $size): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_outline($player, $textdraw, $size);
    }

    public static function setPos(int $player, int $textdraw, float $x, float $y): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_pos($player, $textdraw, $x, $y);
    }

    public static function setPreviewModel(int $player, int $textdraw, int $model): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_preview_model($player, $textdraw, $model);
    }

    public static function setPreviewRot(int $player, int $textdraw, float $rx, float $ry, float $rz, float $zoom): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_preview_rot($player, $textdraw, $rx, $ry, $rz, $zoom);
    }

    public static function setPreviewVehCol(int $player, int $textdraw, int $color1, int $color2): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_preview_veh_col($player, $textdraw, $color1, $color2);
    }

    public static function setProportional(int $player, int $textdraw, bool $set): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_proportional($player, $textdraw, $set);
    }

    public static function setSelectable(int $player, int $textdraw, bool $set): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_selectable($player, $textdraw, $set);
    }

    public static function setShadow(int $player, int $textdraw, int $size): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_shadow($player, $textdraw, $size);
    }

    public static function setString(int $player, int $textdraw, string $text): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_string($player, $textdraw, $text);
    }

    public static function setTextSize(int $player, int $textdraw, float $x, float $y): bool
    {
        return (bool) \Omp\Internal\player_text_draw_set_text_size($player, $textdraw, $x, $y);
    }

    public static function show(int $player, int $textdraw): bool
    {
        return (bool) \Omp\Internal\player_text_draw_show($player, $textdraw);
    }

    public static function useBox(int $player, int $textdraw, bool $use): bool
    {
        return (bool) \Omp\Internal\player_text_draw_use_box($player, $textdraw, $use);
    }

}
