<?php

declare(strict_types=1);

namespace Omp\Api;

// Code generated by tools/codegen. DO NOT EDIT.

final class Recording
{
    public static function start(int $player, int $type, string $file): bool
    {
        return \Omp\Internal\recording_start($player, $type, $file);
    }

    public static function stop(int $player): bool
    {
        return \Omp\Internal\recording_stop($player);
    }

}
