<?php

declare(strict_types=1);

namespace Omp\Api;

// Code generated by tools/codegen. DO NOT EDIT.

final class TextDraw
{
    public static function create(float $x, float $y, string $text): int
    {
        return (int) \Omp\Internal\text_draw_create($x, $y, $text);
    }

    public static function destroy(int $textdraw): bool
    {
        return (bool) \Omp\Internal\text_draw_destroy($textdraw);
    }

    public static function fromId(int $textdrawid): int
    {
        return (int) \Omp\Internal\text_draw_from_id($textdrawid);
    }

    public static function getAlignment(int $textdraw): int
    {
        return (int) \Omp\Internal\text_draw_get_alignment($textdraw);
    }

    public static function getBackgroundColor(int $textdraw): int
    {
        return (int) \Omp\Internal\text_draw_get_background_color($textdraw);
    }

    public static function getBoxColor(int $textdraw): int
    {
        return (int) \Omp\Internal\text_draw_get_box_color($textdraw);
    }

    public static function getColor(int $textdraw): int
    {
        return (int) \Omp\Internal\text_draw_get_color($textdraw);
    }

    public static function getFont(int $textdraw): int
    {
        return (int) \Omp\Internal\text_draw_get_font($textdraw);
    }

    public static function getId(int $textdraw): int
    {
        return (int) \Omp\Internal\text_draw_get_id($textdraw);
    }

    /** @return array{float, float} */
    public static function getLetterSize(int $textdraw): array
    {
        return (array) \Omp\Internal\text_draw_get_letter_size($textdraw);
    }

    public static function getOutline(int $textdraw): int
    {
        return (int) \Omp\Internal\text_draw_get_outline($textdraw);
    }

    /** @return array{float, float} */
    public static function getPos(int $textdraw): array
    {
        return (array) \Omp\Internal\text_draw_get_pos($textdraw);
    }

    public static function getPreviewModel(int $textdraw): int
    {
        return (int) \Omp\Internal\text_draw_get_preview_model($textdraw);
    }

    /** @return array{float, float, float, float} */
    public static function getPreviewRot(int $textdraw): array
    {
        return (array) \Omp\Internal\text_draw_get_preview_rot($textdraw);
    }

    /** @return array{int, int} */
    public static function getPreviewVehColor(int $textdraw): array
    {
        return (array) \Omp\Internal\text_draw_get_preview_veh_color($textdraw);
    }

    public static function getShadow(int $textdraw): int
    {
        return (int) \Omp\Internal\text_draw_get_shadow($textdraw);
    }

    public static function getString(int $textdraw): string
    {
        return (string) \Omp\Internal\text_draw_get_string($textdraw);
    }

    /** @return array{float, float} */
    public static function getTextSize(int $textdraw): array
    {
        return (array) \Omp\Internal\text_draw_get_text_size($textdraw);
    }

    public static function hideForAll(int $textdraw): bool
    {
        return (bool) \Omp\Internal\text_draw_hide_for_all($textdraw);
    }

    public static function hideForPlayer(int $player, int $textdraw): bool
    {
        return (bool) \Omp\Internal\text_draw_hide_for_player($player, $textdraw);
    }

    public static function isBox(int $textdraw): bool
    {
        return (bool) \Omp\Internal\text_draw_is_box($textdraw);
    }

    public static function isProportional(int $textdraw): bool
    {
        return (bool) \Omp\Internal\text_draw_is_proportional($textdraw);
    }

    public static function isSelectable(int $textdraw): bool
    {
        return (bool) \Omp\Internal\text_draw_is_selectable($textdraw);
    }

    public static function isValid(int $textdraw): bool
    {
        return (bool) \Omp\Internal\text_draw_is_valid($textdraw);
    }

    public static function isVisibleForPlayer(int $player, int $textdraw): bool
    {
        return (bool) \Omp\Internal\text_draw_is_visible_for_player($player, $textdraw);
    }

    public static function setAlignment(int $textdraw, int $alignment): bool
    {
        return (bool) \Omp\Internal\text_draw_set_alignment($textdraw, $alignment);
    }

    public static function setBackgroundColor(int $textdraw, int $color): bool
    {
        return (bool) \Omp\Internal\text_draw_set_background_color($textdraw, $color);
    }

    public static function setBoxColor(int $textdraw, int $color): bool
    {
        return (bool) \Omp\Internal\text_draw_set_box_color($textdraw, $color);
    }

    public static function setColor(int $textdraw, int $color): bool
    {
        return (bool) \Omp\Internal\text_draw_set_color($textdraw, $color);
    }

    public static function setFont(int $textdraw, int $font): bool
    {
        return (bool) \Omp\Internal\text_draw_set_font($textdraw, $font);
    }

    public static function setLetterSize(int $textdraw, float $sizeX, float $sizeY): bool
    {
        return (bool) \Omp\Internal\text_draw_set_letter_size($textdraw, $sizeX, $sizeY);
    }

    public static function setOutline(int $textdraw, int $size): bool
    {
        return (bool) \Omp\Internal\text_draw_set_outline($textdraw, $size);
    }

    public static function setPos(int $textdraw, float $x, float $y): bool
    {
        return (bool) \Omp\Internal\text_draw_set_pos($textdraw, $x, $y);
    }

    public static function setPreviewModel(int $textdraw, int $model): bool
    {
        return (bool) \Omp\Internal\text_draw_set_preview_model($textdraw, $model);
    }

    public static function setPreviewRot(int $textdraw, float $rotationX, float $rotationY, float $rotationZ, float $zoom): bool
    {
        return (bool) \Omp\Internal\text_draw_set_preview_rot($textdraw, $rotationX, $rotationY, $rotationZ, $zoom);
    }

    public static function setPreviewVehCol(int $textdraw, int $color1, int $color2): bool
    {
        return (bool) \Omp\Internal\text_draw_set_preview_veh_col($textdraw, $color1, $color2);
    }

    public static function setProportional(int $textdraw, bool $set): bool
    {
        return (bool) \Omp\Internal\text_draw_set_proportional($textdraw, $set);
    }

    public static function setSelectable(int $textdraw, bool $set): bool
    {
        return (bool) \Omp\Internal\text_draw_set_selectable($textdraw, $set);
    }

    public static function setShadow(int $textdraw, int $size): bool
    {
        return (bool) \Omp\Internal\text_draw_set_shadow($textdraw, $size);
    }

    public static function setString(int $textdraw, string $text): bool
    {
        return (bool) \Omp\Internal\text_draw_set_string($textdraw, $text);
    }

    public static function setStringForPlayer(int $textdraw, int $player, string $text): bool
    {
        return (bool) \Omp\Internal\text_draw_set_string_for_player($textdraw, $player, $text);
    }

    public static function setTextSize(int $textdraw, float $sizeX, float $sizeY): bool
    {
        return (bool) \Omp\Internal\text_draw_set_text_size($textdraw, $sizeX, $sizeY);
    }

    public static function setUseBox(int $textdraw, bool $use): bool
    {
        return (bool) \Omp\Internal\text_draw_set_use_box($textdraw, $use);
    }

    public static function showForAll(int $textdraw): bool
    {
        return (bool) \Omp\Internal\text_draw_show_for_all($textdraw);
    }

    public static function showForPlayer(int $player, int $textdraw): bool
    {
        return (bool) \Omp\Internal\text_draw_show_for_player($player, $textdraw);
    }

}
