<?php

declare(strict_types=1);

namespace Omp\Api;

// Code generated by tools/codegen. DO NOT EDIT.

final class Vehicle
{
    public static function addComponent(int $vehicle, int $componentid): bool
    {
        return (bool) \Omp\Internal\vehicle_add_component($vehicle, $componentid);
    }

    public static function addStatic(int $modelid, float $x, float $y, float $z, float $angle, int $color1, int $color2): int
    {
        return (int) \Omp\Internal\vehicle_add_static($modelid, $x, $y, $z, $angle, $color1, $color2);
    }

    public static function addStaticEx(int $modelid, float $x, float $y, float $z, float $angle, int $color1, int $color2, int $respawnDelay, bool $addSiren): int
    {
        return (int) \Omp\Internal\vehicle_add_static_ex($modelid, $x, $y, $z, $angle, $color1, $color2, $respawnDelay, $addSiren);
    }

    public static function attachTrailer(int $trailer, int $vehicle): bool
    {
        return (bool) \Omp\Internal\vehicle_attach_trailer($trailer, $vehicle);
    }

    public static function canHaveComponent(int $modelid, int $componentid): bool
    {
        return (bool) \Omp\Internal\vehicle_can_have_component($modelid, $componentid);
    }

    public static function changeColor(int $vehicle, int $color1, int $color2): bool
    {
        return (bool) \Omp\Internal\vehicle_change_color($vehicle, $color1, $color2);
    }

    public static function changePaintjob(int $vehicle, int $paintjobid): bool
    {
        return (bool) \Omp\Internal\vehicle_change_paintjob($vehicle, $paintjobid);
    }

    public static function colorIndexToColor(int $colorIndex, int $alpha): int
    {
        return (int) \Omp\Internal\vehicle_color_index_to_color($colorIndex, $alpha);
    }

    public static function countOccupants(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_count_occupants($vehicle);
    }

    public static function create(int $modelid, float $x, float $y, float $z, float $rotation, int $color1, int $color2, int $respawnDelay, bool $addSiren): int
    {
        return (int) \Omp\Internal\vehicle_create($modelid, $x, $y, $z, $rotation, $color1, $color2, $respawnDelay, $addSiren);
    }

    public static function destroy(int $vehicle): bool
    {
        return (bool) \Omp\Internal\vehicle_destroy($vehicle);
    }

    public static function detachTrailer(int $vehicle): bool
    {
        return (bool) \Omp\Internal\vehicle_detach_trailer($vehicle);
    }

    public static function enableFriendlyFire(): bool
    {
        return (bool) \Omp\Internal\vehicle_enable_friendly_fire();
    }

    public static function fromId(int $vehicleid): int
    {
        return (int) \Omp\Internal\vehicle_from_id($vehicleid);
    }

    public static function getCab(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_cab($vehicle);
    }

    /** @return array{int, int} */
    public static function getColor(int $vehicle): array
    {
        return (array) \Omp\Internal\vehicle_get_color($vehicle);
    }

    public static function getComponentInSlot(int $vehicle, int $slot): int
    {
        return (int) \Omp\Internal\vehicle_get_component_in_slot($vehicle, $slot);
    }

    public static function getComponentType(int $componentid): int
    {
        return (int) \Omp\Internal\vehicle_get_component_type($componentid);
    }

    /** @return array{int, int, int, int} */
    public static function getDamageStatus(int $vehicle): array
    {
        return (array) \Omp\Internal\vehicle_get_damage_status($vehicle);
    }

    public static function getDistanceFromPoint(int $vehicle, float $x, float $y, float $z): float
    {
        return (float) \Omp\Internal\vehicle_get_distance_from_point($vehicle, $x, $y, $z);
    }

    public static function getDriver(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_driver($vehicle);
    }

    public static function getHealth(int $vehicle): float
    {
        return (float) \Omp\Internal\vehicle_get_health($vehicle);
    }

    public static function getHydraReactorAngle(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_hydra_reactor_angle($vehicle);
    }

    public static function getId(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_id($vehicle);
    }

    public static function getInterior(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_interior($vehicle);
    }

    public static function getLandingGearState(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_landing_gear_state($vehicle);
    }

    public static function getLastDriver(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_last_driver($vehicle);
    }

    /** @return array{float, float, float, float, float, float, float, float, float} */
    public static function getMatrix(int $vehicle): array
    {
        return (array) \Omp\Internal\vehicle_get_matrix($vehicle);
    }

    public static function getMaxPassengerSeats(int $modelid): int
    {
        return (int) \Omp\Internal\vehicle_get_max_passenger_seats($modelid);
    }

    public static function getModel(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_model($vehicle);
    }

    public static function getModelCount(int $modelid): int
    {
        return (int) \Omp\Internal\vehicle_get_model_count($modelid);
    }

    /** @return array{float, float, float} */
    public static function getModelInfo(int $vehiclemodel, int $infotype): array
    {
        return (array) \Omp\Internal\vehicle_get_model_info($vehiclemodel, $infotype);
    }

    public static function getModelsUsed(): int
    {
        return (int) \Omp\Internal\vehicle_get_models_used();
    }

    public static function getNumberPlate(int $vehicle): string
    {
        return (string) \Omp\Internal\vehicle_get_number_plate($vehicle);
    }

    public static function getOccupant(int $vehicle, int $seat): int
    {
        return (int) \Omp\Internal\vehicle_get_occupant($vehicle, $seat);
    }

    public static function getOccupiedTick(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_occupied_tick($vehicle);
    }

    public static function getPaintjob(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_paintjob($vehicle);
    }

    /** @return array{int, int, int, int} */
    public static function getParamsCarDoors(int $vehicle): array
    {
        return (array) \Omp\Internal\vehicle_get_params_car_doors($vehicle);
    }

    /** @return array{int, int, int, int} */
    public static function getParamsCarWindows(int $vehicle): array
    {
        return (array) \Omp\Internal\vehicle_get_params_car_windows($vehicle);
    }

    /** @return array{int, int, int, int, int, int, int} */
    public static function getParamsEx(int $vehicle): array
    {
        return (array) \Omp\Internal\vehicle_get_params_ex($vehicle);
    }

    public static function getParamsSirenState(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_params_siren_state($vehicle);
    }

    /** @return array{float, float, float} */
    public static function getPos(int $vehicle): array
    {
        return (array) \Omp\Internal\vehicle_get_pos($vehicle);
    }

    /** @return array{int, int, int, int} */
    public static function getRandomColorPair(int $modelid): array
    {
        return (array) \Omp\Internal\vehicle_get_random_color_pair($modelid);
    }

    public static function getRespawnDelay(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_respawn_delay($vehicle);
    }

    public static function getRespawnTick(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_respawn_tick($vehicle);
    }

    /** @return array{float, float, float, float} */
    public static function getRotationQuat(int $vehicle): array
    {
        return (array) \Omp\Internal\vehicle_get_rotation_quat($vehicle);
    }

    public static function getSirenState(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_siren_state($vehicle);
    }

    /** @return array{float, float, float, float, int, int} */
    public static function getSpawnInfo(int $vehicle): array
    {
        return (array) \Omp\Internal\vehicle_get_spawn_info($vehicle);
    }

    public static function getTower(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_tower($vehicle);
    }

    public static function getTrailer(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_trailer($vehicle);
    }

    public static function getTrainSpeed(int $vehicle): float
    {
        return (float) \Omp\Internal\vehicle_get_train_speed($vehicle);
    }

    /** @return array{float, float, float} */
    public static function getVelocity(int $vehicle): array
    {
        return (array) \Omp\Internal\vehicle_get_velocity($vehicle);
    }

    public static function getVirtualWorld(int $vehicle): int
    {
        return (int) \Omp\Internal\vehicle_get_virtual_world($vehicle);
    }

    public static function getZAngle(int $vehicle): float
    {
        return (float) \Omp\Internal\vehicle_get_z_angle($vehicle);
    }

    public static function hasBeenOccupied(int $vehicle): bool
    {
        return (bool) \Omp\Internal\vehicle_has_been_occupied($vehicle);
    }

    public static function isDead(int $vehicle): bool
    {
        return (bool) \Omp\Internal\vehicle_is_dead($vehicle);
    }

    public static function isOccupied(int $vehicle): bool
    {
        return (bool) \Omp\Internal\vehicle_is_occupied($vehicle);
    }

    public static function isSirenEnabled(int $vehicle): bool
    {
        return (bool) \Omp\Internal\vehicle_is_siren_enabled($vehicle);
    }

    public static function isStreamedIn(int $vehicle, int $player): bool
    {
        return (bool) \Omp\Internal\vehicle_is_streamed_in($vehicle, $player);
    }

    public static function isTrailerAttached(int $vehicle): bool
    {
        return (bool) \Omp\Internal\vehicle_is_trailer_attached($vehicle);
    }

    public static function isValid(int $vehicle): bool
    {
        return (bool) \Omp\Internal\vehicle_is_valid($vehicle);
    }

    public static function linkToInterior(int $vehicle, int $interiorid): bool
    {
        return (bool) \Omp\Internal\vehicle_link_to_interior($vehicle, $interiorid);
    }

    public static function removeComponent(int $vehicle, int $componentid): bool
    {
        return (bool) \Omp\Internal\vehicle_remove_component($vehicle, $componentid);
    }

    public static function repair(int $vehicle): bool
    {
        return (bool) \Omp\Internal\vehicle_repair($vehicle);
    }

    public static function setAngularVelocity(int $vehicle, float $x, float $y, float $z): bool
    {
        return (bool) \Omp\Internal\vehicle_set_angular_velocity($vehicle, $x, $y, $z);
    }

    public static function setHealth(int $vehicle, float $health): bool
    {
        return (bool) \Omp\Internal\vehicle_set_health($vehicle, $health);
    }

    public static function setNumberPlate(int $vehicle, string $numberPlate): bool
    {
        return (bool) \Omp\Internal\vehicle_set_number_plate($vehicle, $numberPlate);
    }

    public static function setParamsCarDoors(int $vehicle, int $frontLeft, int $frontRight, int $rearLeft, int $rearRight): bool
    {
        return (bool) \Omp\Internal\vehicle_set_params_car_doors($vehicle, $frontLeft, $frontRight, $rearLeft, $rearRight);
    }

    public static function setParamsCarWindows(int $vehicle, int $frontLeft, int $frontRight, int $rearLeft, int $rearRight): bool
    {
        return (bool) \Omp\Internal\vehicle_set_params_car_windows($vehicle, $frontLeft, $frontRight, $rearLeft, $rearRight);
    }

    public static function setParamsEx(int $vehicle, int $engine, int $lights, int $alarm, int $doors, int $bonnet, int $boot, int $objective): bool
    {
        return (bool) \Omp\Internal\vehicle_set_params_ex($vehicle, $engine, $lights, $alarm, $doors, $bonnet, $boot, $objective);
    }

    public static function setParamsForPlayer(int $vehicle, int $player, int $objective, int $doors): bool
    {
        return (bool) \Omp\Internal\vehicle_set_params_for_player($vehicle, $player, $objective, $doors);
    }

    public static function setParamsSirenState(int $vehicle, bool $siren_state): bool
    {
        return (bool) \Omp\Internal\vehicle_set_params_siren_state($vehicle, $siren_state);
    }

    public static function setPos(int $vehicle, float $x, float $y, float $z): bool
    {
        return (bool) \Omp\Internal\vehicle_set_pos($vehicle, $x, $y, $z);
    }

    public static function setRespawnDelay(int $vehicle, int $respawn_delay): bool
    {
        return (bool) \Omp\Internal\vehicle_set_respawn_delay($vehicle, $respawn_delay);
    }

    public static function setSpawnInfo(int $vehicle, int $modelid, float $x, float $y, float $z, float $rotation, int $color1, int $color2, int $respawn_time, int $interior): bool
    {
        return (bool) \Omp\Internal\vehicle_set_spawn_info($vehicle, $modelid, $x, $y, $z, $rotation, $color1, $color2, $respawn_time, $interior);
    }

    public static function setToRespawn(int $vehicle): bool
    {
        return (bool) \Omp\Internal\vehicle_set_to_respawn($vehicle);
    }

    public static function setVelocity(int $vehicle, float $x, float $y, float $z): bool
    {
        return (bool) \Omp\Internal\vehicle_set_velocity($vehicle, $x, $y, $z);
    }

    public static function setVirtualWorld(int $vehicle, int $virtualWorld): bool
    {
        return (bool) \Omp\Internal\vehicle_set_virtual_world($vehicle, $virtualWorld);
    }

    public static function setZAngle(int $vehicle, float $angle): bool
    {
        return (bool) \Omp\Internal\vehicle_set_z_angle($vehicle, $angle);
    }

    public static function toggleSirenEnabled(int $vehicle, bool $status): bool
    {
        return (bool) \Omp\Internal\vehicle_toggle_siren_enabled($vehicle, $status);
    }

    public static function updateDamageStatus(int $vehicle, int $panels, int $doors, int $lights, int $tires): bool
    {
        return (bool) \Omp\Internal\vehicle_update_damage_status($vehicle, $panels, $doors, $lights, $tires);
    }

    public static function useManualEngineAndLights(): bool
    {
        return (bool) \Omp\Internal\vehicle_use_manual_engine_and_lights();
    }

}
